// codebase/admin/src/components/wrap/EditableTextItem.tsx
import { useState } from "react";
import { Button, Input, Space, Tooltip, Typography } from "antd";
import { CheckOutlined } from "@ant-design/icons";
import { CopyIcon, EditIcon } from "../icon/svg/Icons";
import { DefaultNS } from "../../common/I18NNamespace";
import { useTranslation } from "../../hooks/useTranslation";
import { calculateLength } from "../../common/kit";

/**
 * 可编辑的text
 */
export const EditableTextItem : React.FC<{
    value: string,
    onChange?: (value: string) => void, 
    copyable?: boolean,
    editable?: boolean,
    trigger?: 'click' | 'blur',
    type?: 'text' | 'password'
}> = ({
    value, 
    onChange,
    copyable = false,
    editable = true,
    trigger = 'click',
    type = 'text',
}) => {

    const {t} = useTranslation(DefaultNS);
    const [editing, setEdting] = useState(false);
    const [localValue, setLocalValue] = useState(value);
    const [copyed, setCopyed] = useState(false);

    const onEditIconClick = () => {
        setEdting(true);
    }

    const onEnter = ()=> {
        setEdting(false);
        if(localValue !== value && onChange){
            onChange(localValue);
        }
    }

    const onBlur = () => {
        if(trigger == 'blur'){
            onEnter();
        }
    }

    const onClickEnter = () => {
        if(trigger == 'click'){
            onEnter();
        }
    }

    const onCopy = ()=> {
        navigator.clipboard.writeText(value+"");
        setCopyed(true);
        setTimeout(()=>{
            setCopyed(false);
        }, 4000)
    }

    const computeWidth = (str) => {

        let width = calculateLength(str);

        if(!width){
            return 150;
        }else{
            if(width<7){
                return 8*16;
            }else{
                return width * 16;
            }
        }


    }

    if(editing){
        return (
            <Space.Compact>
                {type == 'text'? (
                    <Input value={localValue} onBlur={onBlur}
                        onChange={(e)=>setLocalValue(e.target.value)} 
                        style={{width: computeWidth(value)}}
                    ></Input>
                ): (
                    <Input.Password value={localValue} onBlur={onBlur}
                        onChange={(e)=>setLocalValue(e.target.value)} 
                        style={{width: computeWidth(value)}}
                    ></Input.Password>
                )}
                <Button icon={<CheckOutlined type="primary" />}
                    onClick={onClickEnter}
                ></Button>
            </Space.Compact>
        );
    }else{
        return (
            <>
            <style>{
                `.editable-tag-wrap .copy-icon{display:none;}
                .editable-tag-wrap:hover .copy-icon{display:inline;}
                `
            }</style>
            <div className="editable-tag-wrap" style={{position: 'relative', paddingRight: 30}}>
                <Typography.Text>{value}</Typography.Text>
                <span style={{position: 'absolute', top: 2, right: 0}}>
                    {editable && <Tooltip title={t("编辑")}>
                        {/* {
                            ToolTip需要正常显示，需要动态计算子节点的位置，所以自定义的子节点需要支持ref传递，
                            如果不支持，则会出现警告，所以可以在自定义的子节点外面在包裹一个标准的html节点
                        } */}
                        <span>
                            <EditIcon type="primary" ghost  onClick={onEditIconClick} style={{cursor: 'pointer', marginRight: 5}}/>
                        </span>
                    </Tooltip>}
                    {copyable ? (copyed ? (<CheckOutlined className="copy-icon" style={{color: "#00b96b"}}/>) 
                        : (
                        <Tooltip title={t("复制")}>
                            <span>
                                <CopyIcon type="primary" className="copy-icon" ghost onClick={ onCopy } style={{cursor: 'pointer'}} />
                            </span>
                        </Tooltip>
                        )) : <></>}
                </span>
            </div>
            </>
        );
    }

}

// codebase/admin-vue3/src/components/EditableTextItem.vue
<template>
  <div class="editable-tag-wrap" style="position: relative; padding-right: 30px">
    <template v-if="editing">
      <t-space align="center" class="editable-tag-wrap__edit">
        <t-input
          v-if="type === 'text'"
          v-model="localValue"
          @blur="onBlur"
          :style="inputStyle"
          auto-focus
        />
        <t-input
          v-else
          v-model="localValue"
          type="password"
          @blur="onBlur"
          :style="inputStyle"
          auto-focus
        />
        <t-button theme="primary" variant="text" shape="square" @click="onClickEnter">
          <template #icon><t-icon name="check" /></template>
        </t-button>
      </t-space>
    </template>
    <template v-else>
      <span style="word-break: break-all;">{{ value }}</span>
      <span style="position: absolute; top: 2px; right: 0;">
        <t-tooltip v-if="editable" :content="t('编辑')">
          <span style="cursor: pointer; margin-right: 5px;" @click="onEditIconClick">
            <t-icon name="edit" style="color: var(--td-brand-color)" />
          </span>
        </t-tooltip>
        <template v-if="copyable">
          <t-icon v-if="copyed" name="check" style="color: var(--td-success-color)" />
          <t-tooltip v-else :content="t('复制')">
            <span style="cursor: pointer;" @click="onCopy">
              <t-icon name="file-copy" class="copy-icon" style="color: var(--td-brand-color)" />
            </span>
          </t-tooltip>
        </template>
      </span>
    </template>
  </div>
</template>

<script setup lang="ts">
import { ref, watch, computed } from 'vue';
import { useTranslation } from '@/hooks/useTranslation';

interface Props {
  value: string;
  copyable?: boolean;
  editable?: boolean;
  trigger?: 'click' | 'blur';
  type?: 'text' | 'password';
}

const props = withDefaults(defineProps<Props>(), {
  copyable: false,
  editable: true,
  trigger: 'click',
  type: 'text'
});

const emit = defineEmits<{
  (e: 'change', val: string): void;
}>();

const { t } = useTranslation();
const editing = ref(false);
const localValue = ref(props.value);
const copyed = ref(false);

watch(() => props.value, (val) => {
  localValue.value = val;
});

const onEditIconClick = () => {
  editing.value = true;
};

const onEnter = () => {
  editing.value = false;
  if (localValue.value !== props.value) {
    emit('change', localValue.value);
  }
};

const onBlur = () => {
  if (props.trigger === 'blur') {
    onEnter();
  }
};

const onClickEnter = () => {
  if (props.trigger === 'click') {
    onEnter();
  }
};

const onCopy = () => {
  navigator.clipboard.writeText(props.value || '');
  copyed.value = true;
  setTimeout(() => {
    copyed.value = false;
  }, 4000);
};

const computeWidth = (str: string) => {
  if (!str) return 150;
  let length = 0;
  for (let i = 0; i < str.length; i++) {
    if (str.charCodeAt(i) > 127) {
      length += 2;
    } else {
      length += 1;
    }
  }
  return length < 7 ? 8 * 16 : length * 16;
};

const inputStyle = computed(() => {
  const w = Math.min(computeWidth(props.value), 560);
  return {
    width: '100%',
    maxWidth: `${w}px`,
    flex: 1,
    minWidth: '180px',
  };
});

</script>

<style scoped>
.editable-tag-wrap__edit {
  width: 100%;
}

.editable-tag-wrap .copy-icon {
  display: none;
}
.editable-tag-wrap:hover .copy-icon {
  display: inline-block;
}
</style>
