// codebase/admin-vue3/src/pages/sys/dept/EditableDeptItem.vue
<template>
  <div class="editable-tag-wrap" style="position: relative; padding-right: 30px">
    <template v-if="editing">
      <t-space align="center">
        <DeptSelector
          v-model="localValue.value"
          style="width: calc(100% - 50px)"
          @change="onSelect"
        />
        <t-button theme="primary" variant="text" shape="square" @click="onEnter">
          <template #icon><t-icon name="check" /></template>
        </t-button>
      </t-space>
    </template>
    <template v-else>
      <span>{{ deptName }}<br/>{{ deptPath }}<br/>{{ deptPathName }}</span>
      <span style="position: absolute; top: 2px; right: 0;">
        <t-tooltip v-if="editable" :content="t('编辑')">
          <span style="cursor: pointer; margin-right: 5px;" @click="onEditIconClick">
            <t-icon name="edit" style="color: var(--td-brand-color)" />
          </span>
        </t-tooltip>
        <template v-if="copyable">
          <t-icon v-if="copyed" name="check" style="color: var(--td-success-color)" />
          <t-tooltip v-else :content="t('复制')">
            <span style="cursor: pointer;" @click="onCopy">
              <t-icon name="file-copy" class="copy-icon" style="color: var(--td-brand-color)" />
            </span>
          </t-tooltip>
        </template>
      </span>
    </template>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue';
import { useTranslation } from '@/hooks/useTranslation';
import DeptSelector from '@/pages/sys/dept/DeptSelector.vue';
import { AdminDept } from '@/utils/I18NNamespace';

interface Props {
  value: number;
  deptName: string;
  deptPath: string;
  deptPathName: string;
  editable?: boolean;
  copyable?: boolean | 'CopyValue' | 'CopyLabel' | 'CopyAll';
}

const props = withDefaults(defineProps<Props>(), {
  copyable: false,
  editable: true,
});

const emit = defineEmits<{
  (e: 'change', val: number, obj: any): void;
}>();

const { t } = useTranslation(AdminDept);
const editing = ref(false);
const copyed = ref(false);

const localValue = ref({
  value: props.value,
  deptName: props.deptName,
  deptPath: props.deptPath,
  deptPathName: props.deptPathName
});

watch(() => props.value, () => {
  localValue.value = {
    value: props.value,
    deptName: props.deptName,
    deptPath: props.deptPath,
    deptPathName: props.deptPathName
  };
});

const onEditIconClick = () => {
  editing.value = true;
};

const onEnter = () => {
  editing.value = false;
  if (localValue.value.value !== props.value) {
    emit('change', localValue.value.value, localValue.value);
  }
};

const onSelect = (value: any, context: any) => {
  if (context && context.node) {
    const node = context.node.data;
    localValue.value = {
      value: value,
      deptName: node.name,
      deptPath: node.path,
      deptPathName: node.pathName
    };
  }
};

const onCopy = () => {
  let text = "";
  if (props.copyable === 'CopyLabel') {
    text = localValue.value.deptName + "";
  } else if (props.copyable === 'CopyAll') {
    text = JSON.stringify(localValue.value);
  } else {
    text = props.value + "";
  }
  
  navigator.clipboard.writeText(text);
  copyed.value = true;
  setTimeout(() => {
    copyed.value = false;
  }, 4000);
};
</script>

<style scoped>
.editable-tag-wrap .copy-icon {
  display: none;
}
.editable-tag-wrap:hover .copy-icon {
  display: inline-block;
}
</style>

// codebase/admin/src/pages/sys/dept/EditableDeptItem.tsx
import { CheckOutlined } from "@ant-design/icons";
import { Button, Space, Tooltip, Typography } from "antd";
import { useState } from "react";
import { AdminDept } from "../../../common/I18NNamespace";
import { useTranslation } from "../../../hooks";
import { CopyIcon, EditIcon } from "../../../components/icon/svg/Icons";
import { DeptSelectorWraper } from ".";

/**
 * 可编辑的dept， 参考UserEditBasicInfo.tsx
 */
export const EditableDeptItem : React.FC<{
    value: number,
    deptName: string,
    deptPath: string, 
    deptPathName: string,
    onChange?: (value: number, obj: any) => void, 
    editable?: boolean,
    copyable?: boolean | 'CopyValue' | 'CopyLabel' | 'CopyAll',
}> = ({
    value, 
    deptPath,
    deptName,
    deptPathName,
    onChange,
    copyable = false,
    editable = true,
}) => {

    const {t} = useTranslation(AdminDept);
    const [editing, setEdting] = useState(false);
    const [localValue, setLocalValue] = useState({
        value,
        deptName,
        deptPath,
        deptPathName
    });
    const [copyed, setCopyed] = useState(false);

    const onEditIconClick = () => {
        setEdting(true);
    }

    const onEnter = ()=> {
        setEdting(false);
        if(localValue.value !== value && onChange){
            onChange(localValue.value, localValue);
        }
    }

    const onCopy = ()=> {
        let text = "";
        if(copyable == 'CopyLabel'){
            text = localValue.deptName + "";
        }else if(copyable == 'CopyAll'){
            text = JSON.stringify(localValue);
        }else{
            text = value+"";
        }
        navigator.clipboard.writeText(text+"");
        setCopyed(true);
        setTimeout(()=>{
            setCopyed(false);
        }, 4000)
    }

    // const onInputChange = (value) => {
        // console.log(value);
        // setLocalValue(e.target.value*1 || 0 );
        // setLocalValue(value)
    // }

    const onSelect = (value, node) => {
        // console.log(value, node);
        setLocalValue({
            value: value,
            deptName: node.name,
            deptPath: node.path,
            deptPathName: node.pathName
        })
    }

    if(editing){
        return (
            <Space.Compact block>
                <DeptSelectorWraper value={localValue} 
                    onSelect={onSelect}
                    showName={deptPathName}
                    wrapStyle={{width: 'calc(100% - 50px)'}}
                    showNamePos={{
                        bottom: 4,
                        left : 10
                    }}
                />
                <Button icon={<CheckOutlined type="primary" />}
                    onClick={onEnter}
                ></Button>
            </Space.Compact>
        );
    }else{
        return (
            <>
            <style>{
                `.editable-tag-wrap .copy-icon{display:none;}
                .editable-tag-wrap:hover .copy-icon{display:inline;}
                `
            }</style>
            <div className="editable-tag-wrap" style={{position: 'relative', paddingRight: 30}}>
                <Typography.Text>{deptName}<br/>{deptPath}<br/>{deptPathName}</Typography.Text>
                <span style={{position: 'absolute', top: 2, right: 0}}>
                    {editable && <Tooltip title={t("编辑")}>
                        {/* {
                            ToolTip需要正常显示，需要动态计算子节点的位置，所以自定义的子节点需要支持ref传递，
                            如果不支持，则会出现警告，所以可以在自定义的子节点外面在包裹一个标准的html节点
                        } */}
                        <span>
                            <EditIcon type="primary" ghost  onClick={onEditIconClick} style={{cursor: 'pointer', marginRight: 5}}/>
                        </span>
                    </Tooltip>}
                    {copyable ? (copyed ? (<CheckOutlined className="copy-icon" style={{color: "#00b96b"}}/>) 
                        : (
                        <Tooltip title={t("复制")}>
                            <span>
                                <CopyIcon type="primary" className="copy-icon" ghost onClick={ onCopy } style={{cursor: 'pointer'}} />
                            </span>
                        </Tooltip>
                        )) : <></>}
                </span>
            </div>
            </>
        );
    }

}
