// codebase/admin/src/pages/sys/user/UserGrantRoleModal.tsx
import { useState } from "react"
import { Modal } from "../../../components"
import { UserGrantRole } from "./UserGrantRole"
import { CustomScroll } from "react-custom-scroll"


export const UserGrantRoleModal : React.FC<{
    open: boolean,
    userId: number,
    onClose: () => void,
}> = ({
    open,
    userId,
    onClose
}) => {
    const [visible, setVisible] = useState(open)
    const onModalClose = () => {
        setVisible(false);
        setTimeout(() => {
            onClose();
        }, 500);
    }

    return <Modal open={visible} onClose={onModalClose} height={250} width={350}>
        <CustomScroll heightRelativeToParent="100%" >
            <UserGrantRole userId={userId} titleLevel={4} 
                titleStyle={{textAlign: 'center', margin: '25px 0 15px 0'}} 
                wrapperStyle={{paddingLeft: 20, paddingRight: 20}}    
            />
        </CustomScroll>
    </Modal>
}

// codebase/admin-vue3/src/pages/sys/user/UserGrantRoleModal.vue
<template>
    <Modal :open="visible" :width="500" :height="300" @close="onModalClose">
        <div style="height: 100%; overflow: auto;">
            <UserGrantRole :user-id="userId" :title-level="4"
                :title-style="{ textAlign: 'center', margin: '25px 0 15px 0' }"
                :wrapper-style="{ paddingLeft: '20px', paddingRight: '20px' }" />
        </div>
    </Modal>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue';
import Modal from '@/components/Modal/index.vue';
import UserGrantRole from './UserGrantRole.vue';

const props = defineProps<{
    open: boolean;
    userId: number;
}>();

const emit = defineEmits<{
    (e: 'close'): void;
    (e: 'update:open', val: boolean): void;
}>();

const visible = ref(props.open);

watch(() => props.open, (val) => {
    visible.value = val;
});

const onModalClose = () => {
    visible.value = false;
    emit('update:open', false);
    setTimeout(() => {
        emit('close');
    }, 500);
};
</script>
