// codebase/admin/src/pages/sys/user/UserGrantRole.tsx
import { Space, Tag, theme, Typography } from "antd"
import { AdminUser, DefaultNS } from "../../../common/I18NNamespace"
import { useLayer } from "../../../components"
import { useRequest, useShowResult, useTranslation } from "../../../hooks"
import { useEffect, useRef, useState } from "react"
import { useDict } from "../../../common/dict"
import { PlusOutlined } from "@ant-design/icons"
import { RoleSelector } from "../role"
import { api } from "../../../common/api"


export const UserGrantRole : React.FC<{
    userId: number,
    titleLevel?: 1|2|3|4|5,
    titleStyle?: {
        [key: string]: string | number
    },
    wrapperStyle?: {
        [key: string]: string | number
    },
}> = ({
    userId,
    titleLevel,
    titleStyle,
    wrapperStyle
}) => {
    
    const {t, f} = useTranslation(AdminUser);
    const request = useRequest();
    const {confirm, message, destory} = useLayer();
    const  [confirmId, setConfirmId] = useState<string>();
    const [userRoles, setUserRoles] = useState<any[]>();
    const roleTypes = useDict("RoleType");
    const { token } = theme.useToken();
    const selectRoleRef = useRef<any>();
    const showResult = useShowResult(AdminUser);

    const getUserRoles = async ()=> {
        let result = await request.get(api.user.userRoles+"?id="+userId);
        if(result.status){
            setUserRoles(result.data);
        }
    }

    useEffect(()=>{
        getUserRoles();
    }, []);

    //删除用户角色
    const onDelete = (role) => {
        confirm({
            title: t("删除用户角色"),
            content: f("确定要删用户的角色%s？", [role.roleName]),
            onOk: (close) => {
                let deleteUserRole = async () => {
                    let result = await request.get(api.user.userRoleDelete+"?id="+role.id);
                    showResult.show(result);
                    if(result.status){
                        getUserRoles();
                        close();
                    }
                }
                deleteUserRole();
            }
        });
    }

    //提交新增
    const submitAdd = async () => {
        let selectedRole = selectRoleRef.current;
        if(!selectedRole || selectedRole.length== 0 || !selectedRole[0].key){
            message.warning("请选择角色");
            return;
        }

        let result = await request.get(api.user.userRoleAdd+"?id="+userId+"&rid="+selectedRole[0].key);
        showResult.show(result);
        if(result.status){
            getUserRoles();
            setConfirmId(prevId => {
                destory(prevId);
                return null;
            });
        }
    }

    //添加用户角色
    const onAdd = () => {
        let id = confirm({
            title: t("请选择角色"),
            content: (<div style={{marginTop: 15}}>
                <RoleSelector mode="single" onChange={(value) => selectRoleRef.current = value} />
            </div>),
            onOk: () => {
                submitAdd();
            },
            width: 300,
            height: 220
        });
        setConfirmId(id);
    }

    return <div style={wrapperStyle}>
        <div style={{position: 'relative'}}>
            <Typography.Title level={titleLevel}  style={titleStyle} >
                {t("数据权限")}
            </Typography.Title>
        </div>
        <Space wrap>
            {userRoles && userRoles.map(r => (
                <Tag key={r.id} color={roleTypes?.find(rt => rt.value == r.type)?.color}
                    closable onClose={() => onDelete(r)}
                >{r.roleName + "("+r.code+")"}
                </Tag>
            ))}
            <Tag onClick={onAdd} 
                style={{background: token.colorBgContainer,borderStyle: 'dashed',
                    cursor: 'pointer'
                }}
            >
                <PlusOutlined /> {t('添加角色')}
            </Tag>
        </Space>
    </div>
}

// codebase/admin-vue3/src/pages/sys/user/UserGrantRole.vue
<template>
    <div :style="wrapperStyle">
        <div style="position: relative;">
            <component :is="`h${titleLevel}`" :style="titleStyle">
                {{ t('分配角色') }}
            </component>
        </div>

        <t-space break-line>
            <t-tag v-for="r in userRoles" :key="r.id" theme="primary" :color="getRoleCustomColor(r.type)"
                variant="light-outline" closable @close="onDelete(r)">
                {{ `${r.roleName}(${r.code})` }}
            </t-tag>

            <t-tag style="background: var(--td-bg-color-container); border-style: dashed; cursor: pointer;"
                @click="onAdd">
                <template #icon><t-icon name="add" /></template>
                {{ t('添加角色') }}
            </t-tag>
        </t-space>
    </div>
</template>

<script setup lang="ts">
import { ref, onMounted, h } from 'vue';
import { useTranslation } from '@/hooks/useTranslation';
import { useLayer } from '@/hooks/useLayer';
import { useRequest } from '@/hooks/useRequest';
import { useShowResult } from '@/hooks/useShowResult';
import { useDictStore } from '@/store/modules/dict';
import { api } from '@/utils/api';
import RoleSelector from '../role/RoleSelector.vue';
import { AdminUser } from '@/utils/I18NNamespace';

const props = withDefaults(defineProps<{
    userId: number;
    titleLevel?: number;
    titleStyle?: any;
    wrapperStyle?: any;
}>(), {
    titleLevel: 5
});

const { t, f } = useTranslation(AdminUser);
const request = useRequest();
const { confirm, message } = useLayer();
const showResult = useShowResult(AdminUser);
const dictStore = useDictStore();

const userRoles = ref<any[]>([]);
const selectRoleValue = ref<any>(null);

const getUserRoles = async () => {
    const result = await request.get(`${api.user.userRoles}?id=${props.userId}`);
    if (result.status) {
        const data: any = result.data;
        userRoles.value = Array.isArray(data) ? data : Array.isArray(data?.list) ? data.list : [];
    }
};

onMounted(() => {
    dictStore.getDict('RoleType');
    getUserRoles();
});

const getRoleColor = (type: any) => {
    const roleTypes = dictStore.dicts['RoleType'] || [];
    const rt = roleTypes.find((r) => r.value == type);
    return rt?.color || '';
};

const getRoleCustomColor = (type: any) => {
    const c = getRoleColor(type);
    const allowed = ['default', 'primary', 'success', 'warning', 'danger'];
    if (!c || (typeof c === 'string' && allowed.includes(c))) return undefined;
    return c;
};


const onDelete = (role: any) => {
    confirm({
        title: t('删除用户角色'),
        content: f('确定要删用户的角色%s？', [role.roleName]),
        onOk: async (close) => {
            const result = await request.get(`${api.user.userRoleDelete}?id=${role.id}`);
            showResult.show(result);
            if (result.status) {
                getUserRoles();
                close();
            }
        }
    });
};

const submitAdd = async (closeFn: Function) => {
    if (!selectRoleValue.value) {
        message.warning(t('请选择角色'));
        return;
    }

    // Handle both array and single value structures from RemoteSelect
    let rid = null;
    if (Array.isArray(selectRoleValue.value) && selectRoleValue.value.length > 0) {
        rid = selectRoleValue.value[0];
    } else {
        rid = selectRoleValue.value;
    }

    const result = await request.get(`${api.user.userRoleAdd}?id=${props.userId}&rid=${rid}`);
    showResult.show(result);
    if (result.status) {
        getUserRoles();
        closeFn();
    }
};

const onAdd = () => {
    selectRoleValue.value = null;

    confirm({
        title: t('请选择角色'),
        width: 300,
        content: h('div', { style: { marginTop: '15px' } }, [
            h(RoleSelector, {
                mode: 'single',
                modelValue: selectRoleValue.value,
                'onUpdate:modelValue': (val: any) => { selectRoleValue.value = val; }
            })
        ]),
        onOk: (closeFn) => {
            submitAdd(closeFn);
        }
    });
};
</script>

<style scoped>
:deep(.t-tag__close) {
    color: inherit;
}
</style>
