// codebase/admin/src/pages/sys/user/UserEditBasicInfo.tsx
import { Col, Descriptions, Row, Typography, DescriptionsProps } from "antd"
import { FileUploadFormItem } from "../document"
import { useTranslation } from "../../../hooks"
import { EditableTagItem, EditableTextItem } from "../../../components"
import { AdminDept, AdminUser } from "../../../common/I18NNamespace";
import { UserProps } from "./UserType";
import { EditableDeptItem } from "../dept/index";
import { useDict } from "../../../common/dict";

/**
 * 编辑用户的基本信息
 */
export const UserEditBasicInfo : React.FC<{
    onHandleChange: (key: string, value: any) => void,
    onUpdateUser: (updateUser, key) => void,
    user: UserProps,
    modalPos: any
}> = ({
    onHandleChange,
    onUpdateUser,
    user,
    modalPos
}) => {

    const userStatus = useDict('UserStatus');
    const genders = useDict('Gender');
    const {t} = useTranslation(AdminUser);

    //删除照片的回调事件
    const onPhotoRemove = (value) => {
        onUpdateUser({
            id: user['id'],
            photo: 0,
        }, 'photo');
    } 

    const basicItems: DescriptionsProps['items'] = [
        {
            key: "fullname",
            label: t('姓名'),
            span: 1,
            children:  <EditableTextItem value={user.fullname} copyable
                            onChange={(value)=>onHandleChange("fullname",value)} 
                        ></EditableTextItem>
        },
        {
            key: "gender",
            label: t('性别'),
            span: 1,
            children: <EditableTagItem value={user.gender} options={genders} width={60}
                    i18nNamespace={AdminDept} copyable='CopyLabel' editable
                    onChange={(value)=>onHandleChange("gender",value)} 
                />
        },
        {
            key: "status",
            label: t('状态'),
            span: modalPos.width>768?1:(modalPos.width>500?2: 1),
            children: <EditableTagItem value={user.status} options={userStatus} width={80}
                        i18nNamespace={AdminUser} copyable='CopyLabel' editable
                        onChange={(value)=>onHandleChange("status",value)} 
                    />
        },
        {
            key: "deptId",
            label: t('所在组织'),
            span: modalPos.width>768?3:(modalPos.width>500?2: 1),
            children: <EditableDeptItem copyable="CopyAll" editable
                        value={user.deptId} deptName={user.deptName} deptPath={user.deptPath} deptPathName={user.deptPathName}
                        onChange={(value, obj)=>onHandleChange("deptId", obj)} 
                    />
        },
    ];

    return <>
        <div>
            <Typography.Title level={5} style={{marginTop: 5, marginBottom: 20}}>{t("基本信息")}</Typography.Title>
            <Row style={{marginBottom: 15}} justify="center">
                <Col>
                    <FileUploadFormItem category="photo" listType="picture-circle" maxCount={1} value={[user.photo]}
                        onChange={(values) => onHandleChange('photo', values[0])}
                        onRemove={onPhotoRemove}
                    />
                </Col>
                <Col style={{paddingLeft: 30}}>
                    <Typography.Paragraph>
                        <b>{t("ID")}： </b>{user.id}
                        <span style={{marginLeft: 35}}><b>{t("推广码")}： </b>{user.code}</span>
                    </Typography.Paragraph>
                    <Typography.Paragraph><b>{t("用户名")}： </b>{user.username}</Typography.Paragraph>
                    <Typography.Paragraph><b>{t("注册时间")}： </b>{user.created}</Typography.Paragraph>
                </Col>
            </Row>
        </div>
        <Descriptions className="user-basic-info" bordered items={basicItems} 
            column={modalPos.width>768?3:(modalPos.width>500?2: 1)} />
    </>

}

// codebase/admin-vue3/src/pages/sys/user/UserEditBasicInfo.vue
<template>
  <div>
    <t-space align="center" style="margin-bottom: 20px;">
      <h5 style="margin: 0">{{ t('基本信息') }}</h5>
    </t-space>
    
    <t-row :gutter="24" style="margin-bottom: 15px;" justify="center">
      <t-col>
        <t-upload
          v-model="photoValue"
          theme="image"
          accept="image/*"
          :action="uploadAction"
          :with-credentials="true"
          :format-response="formatUploadResponse"
          :max="1"
        />
      </t-col>
      <t-col style="padding-left: 30px;">
        <p>
          <b>{{ t('ID') }}：</b> {{ user.id }}
          <span style="margin-left: 35px;"><b>{{ t('推广码') }}：</b> {{ user.code }}</span>
        </p>
        <p><b>{{ t('用户名') }}：</b> {{ user.username }}</p>
        <p><b>{{ t('注册时间') }}：</b> {{ user.created }}</p>
      </t-col>
    </t-row>

    <t-descriptions bordered :column="columnCount" class="user-basic-info">
      <t-descriptions-item :label="t('姓名')">
        <EditableTextItem
          :value="user.fullname"
          copyable
          @change="(val) => onHandleChange('fullname', val)"
        />
      </t-descriptions-item>
      
      <t-descriptions-item :label="t('性别')">
        <EditableTagItem
          :value="user.gender"
          :options="genders"
          copyable="CopyLabel"
          :width="60"
          @change="(val) => onHandleChange('gender', val)"
        />
      </t-descriptions-item>
      
      <t-descriptions-item :label="t('状态')" :span="columnCount === 1 ? 1 : (columnCount === 3 ? 1 : 2)">
        <EditableTagItem
          :value="user.status"
          :options="userStatus"
          copyable="CopyLabel"
          :width="80"
          @change="(val) => onHandleChange('status', val)"
        />
      </t-descriptions-item>
      
      <t-descriptions-item :label="t('所在组织')" :span="columnCount === 1 ? 1 : (columnCount === 3 ? 3 : 2)">
        <EditableDeptItem
          :value="user.deptId"
          :dept-name="user.deptName"
          :dept-path="user.deptPath"
          :dept-path-name="user.deptPathName"
          copyable="CopyAll"
          @change="(val, obj) => onHandleChange('deptId', obj)"
        />
      </t-descriptions-item>
    </t-descriptions>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch, onMounted } from 'vue';
import { useTranslation } from '@/hooks/useTranslation';
import { useDict } from '@/hooks/useDict';
import { api } from '@/utils/api';
import EditableTextItem from '@/components/EditableTextItem.vue';
import EditableTagItem from '@/components/EditableTagItem.vue';
import EditableDeptItem from '../dept/EditableDeptItem.vue';
import { computePx } from '@/utils/kit';
import { AdminUser } from '@/utils/I18NNamespace';

const props = defineProps<{
  user: any;
  modalPos: any;
  vertical?: boolean;
}>();

const emit = defineEmits<{
  (e: 'handleChange', key: string, value: any): void;
  (e: 'updateUser', updateUser: any, key: string): void;
}>();

const { t } = useTranslation(AdminUser);
const userStatus = useDict('UserStatus');
const genders = useDict('Gender');

const uploadUrl = api.document.upload;
const photoValue = ref<any[]>([]);

const buildPhotoUrl = (photo: any) => {
  if (photo === undefined || photo === null || photo === '' || photo === 0) return '';
  const s = String(photo);
  if (/^\d+$/.test(s)) return `${api.document.img}?id=${s}`;
  return s;
};
const uploadType = 'photo';
const uploadPress = 1;
const uploadAction = computed(() => `${uploadUrl}?type=${encodeURIComponent(uploadType)}&press=${uploadPress}`);

onMounted(() => {
  if (props.user.photo) {
    photoValue.value = [{ url: buildPhotoUrl(props.user.photo) }];
  }
});

const formatUploadResponse = (response: any) => {
  console.log("response", response);
  if (response?.error) {
    return { error: String(response.error), status: 'fail' };
  }

  if(!response.status){
    return { error: String(response.error), status: 'fail' };
  }

  const pid = response?.data;
  const previewUrl = `${api.document.img}?id=${pid}`;
  emit('handleChange', 'photo', pid);
  
  return { status: 'success', url: previewUrl, id: pid };
};

const columnCount = computed(() => {
  if (props.vertical) return 1;
  if (!props.modalPos?.width) return 3;
  const w = computePx(props.modalPos.width);
  if (w > 768) return 3;
  if (w > 500) return 2;
  return 1;
});

const onHandleChange = (key: string, value: any) => {
  emit('handleChange', key, value);
};
</script>
