// codebase/admin-vue3/src/pages/sys/history/HistoryQuery.vue
<template>
    <QueryComponent :items="queryItems" @query="onQueryEvent" />
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useTranslation } from '@/hooks/useTranslation';
import QueryComponent from '@/components/QueryComponent.vue';
import UserSelector from '../user/UserSelector.vue';
import dayjs from 'dayjs';
import { AdminHistory } from '@/utils/I18NNamespace';

const emit = defineEmits<{
    (e: 'query', values: any): void;
}>();

const { t } = useTranslation(AdminHistory);

const queryItems = computed(() => [
    { label: t('操作人'), name: 'userId', component: UserSelector, props: { mode: 'single', clearable: true } },
    { label: t('IP地址'), name: 'ipAddr', component: 't-input', props: { clearable: true } },
    { label: t('操作类型'), name: 'type', component: 't-input', props: { clearable: true } },
    { label: t('请求参数'), name: 'remark', component: 't-input', props: { clearable: true } },
    { label: t('操作时间'), name: 'created', component: 't-date-range-picker', props: { clearable: true, allowInput: true }, width: 360 },
]);

const onQueryEvent = (values: any) => {
    const v: any = { ...values };

    if (v.userId !== undefined && v.userId !== null && v.userId !== '') {
        v.userId = Number(v.userId);
    }

    if (v.created && Array.isArray(v.created) && v.created.length === 2) {
        v.startDate = dayjs(v.created[0]).format('YYYY-MM-DD');
        v.endDate = dayjs(v.created[1]).format('YYYY-MM-DD');
        delete v.created;
    }

    emit('query', v);
};
</script>

// codebase/admin/src/pages/history/HistoryQueryComponent.tsx
import { QueryComponent, useTranslation } from '../../components';
import { Input, DatePicker } from "antd"
import { useSelector } from '../../redux/hooks';
import { UserSelector } from '../index';
import { AdminHistory } from '../../common/I18NNamespace';

const { RangePicker } = DatePicker;

export type HisotyrQueryComponentType = {
    onQuery: (values) => void         //点击查询后，获取到的字段集合
}

export const HistoryQueryComponent: React.FC<HisotyrQueryComponentType> = ({onQuery}) => {

    const size = useSelector(state => state.themeConfig.componentSize);
    const  {t} = useTranslation(AdminHistory);

    const queryItems = [
        {
            label: t("操作人"),
            name: "userId",
            inputElement: <UserSelector name="userId" mode='single' size={size} allowClear/>
        },
        {
            label: t("IP地址"),
            name: "ipAddr",
            inputElement: <Input name="fullname" size={size} allowClear/>
        },
        {
            label: '操作类型',
            name: "type",
            inputElement: <Input name="email" size={size} allowClear/>
        },
        {
            label: t("请求参数"),
            name: "remark",
            inputElement: <Input name="phone" size={size} allowClear/>
        },
         {
            label: t("操作时间"),
            name: "created",
            inputElement: <RangePicker name="created" size={size} allowClear/>
        },
    ]

    let onQueryEvent = (values) => {

        if(values.userId){
            // [{"label": "普通管理员(admin)", "value": "3", "key": "3"}]
            values.userId = values.userId[0].key*1;
        }

        if(values.created){
            let start = values.created[0].format("YYYY-MM-DD");
            let end = values.created[1].format("YYYY-MM-DD");
            // console.log(start, end);
            values['startDate'] = start;
            values['endDate'] = end;
            delete values.created
        }

        if(values.userId){
            values.userId = values.userId[0].value;
        }

        onQuery(values);
    }

    return <>
        <QueryComponent items={queryItems} onQuery={onQueryEvent} />
    </>
}
