// codebase/admin-vue3/src/pages/sys/history/HistoryDetail.vue
<template>
  <Modal
    :open="visible"
    :title="t('日志详情')"
    :width="600"
    :show-mask="false"
    :offset-x="offsetX"
    :offset-y="offsetY"
    @close="onCloseModal"
  >
    <div style="padding: 10px 20px;">
      <t-skeleton v-if="loading" animation="flashed" />
      
      <t-descriptions v-else bordered :column="columnCount">
        <t-descriptions-item :label="t('操作人')">{{ detail?.username }}</t-descriptions-item>
        <t-descriptions-item :label="t('IP地址')">{{ detail?.ipAddr }}</t-descriptions-item>
        <t-descriptions-item :label="t('操作类型')">{{ detail?.type }}</t-descriptions-item>
        <t-descriptions-item :label="t('操作时间')">{{ detail?.created }}</t-descriptions-item>
        <t-descriptions-item :label="t('请求参数')" :span="columnCount">
          <span style="word-break: break-all;">
            {{ detail?.remark }}
          </span>
        </t-descriptions-item>
      </t-descriptions>
    </div>
  </Modal>
</template>

<script setup lang="ts">
import { ref, watch, onMounted, computed, inject } from 'vue';
import Modal from '@/components/Modal/index.vue';
import { useTranslation } from '@/hooks/useTranslation';
import { useRequest } from '@/hooks/useRequest';
import { useShowResult } from '@/hooks/useShowResult';
import { api } from '@/utils/api';
import { computePx } from '@/utils/kit';
import { AdminHistory } from '@/utils/I18NNamespace';

const props = defineProps<{
  historyId: number | string;
  open: boolean;
  offsetX?: number;
  offsetY?: number;
}>();

const emit = defineEmits<{
  (e: 'close'): void;
  (e: 'update:open', val: boolean): void;
}>();

const { t } = useTranslation(AdminHistory);
const request = useRequest();
const showResult = useShowResult(AdminHistory);
const offsetX = computed(() => props.offsetX ?? 0);
const offsetY = computed(() => props.offsetY ?? 0);

const visible = ref(props.open);
const loading = ref(true);
const detail = ref<any>(null);

const modalPos = inject<any>('modalContext', null);

const columnCount = computed(() => {
  if (!modalPos?.value?.width) return 2;
  const w = computePx(modalPos.value.width);
  if (w > 500) return 2;
  return 1;
});

const getDetail = async () => {
  if (!props.historyId) return;
  
  loading.value = true;
  const result = await request.get(`${api.history.get}?historyId=${props.historyId}`);
  showResult.show(result);

  if (result.status) {
    detail.value = result.data;
    loading.value = false;
  }
};

onMounted(() => {
  if (props.open && props.historyId) {
    getDetail();
  }
});

watch(() => [props.open, props.historyId], ([newOpen, newId]) => {
  visible.value = newOpen as boolean;
  if (newOpen && newId) {
    getDetail();
  }
});

const onCloseModal = () => {
  visible.value = false;
  emit('update:open', false);
  setTimeout(() => {
    emit('close');
  }, 300);
};
</script>

// codebase/admin/src/pages/history/HistoryDetail.tsx


import { useEffect, useState } from 'react';
import { Descriptions, DescriptionsProps, Skeleton, theme as antdTheme, App  } from 'antd';
import { useSelector } from '../../redux/hooks';
import { Modal, useRequest, useTranslation } from '../../components';
import { api } from '../../common/api';
import { AdminHistory, DefaultNS } from '../../common/I18NNamespace';

export type HistoryDetailType = {
    historyId: string,
    open: boolean
    close: () => void
}

export const HistoryDetail : React.FC<HistoryDetailType> = ({
    historyId = 0,
    open = false,
    close,
}) => {

    // if(!(open && historyId)){
    //     return <></>
    // }

    const [loading, setLoading] = useState(true);
    const theme = useSelector(state => state.themeConfig.theme);
    const { message } = App.useApp();

    const [items, setItems] = useState<DescriptionsProps['items']>();
    const size = useSelector(state => state.themeConfig.componentSize);
    const request = useRequest();
    const {token} = antdTheme.useToken();
    const {t} = useTranslation(AdminHistory);

    useEffect(()=>{
        if(!historyId) return;
        getDetail();
    }, [open, historyId]);

    const getDetail = async () => {
        let result = await request.get(api.history.get+"?historyId="+historyId);
        if(result.status){
            let hist = result.data;
            setItems([
                {
                    label: t("操作人"),
                    children: hist.username
                },
                {
                    label: t("IP地址"),
                    children: hist.ipAddr
                },
                {
                    label: t("操作类型"),
                    children: hist.type
                },
                {
                    label: t("操作时间"),
                    children: hist.created
                },
                {
                    label: t("请求参数"),
                    children: hist.remark,
                    span: { xs: 2, sm: 2, md: 2, lg: 2, xl: 2, xxl: 2 },
                }
            ]);
            setLoading(false);
            message.success(t(result.msg, DefaultNS));
        }else{
            message.error(t(result.msg, DefaultNS));
        }
    }

    return <>
        <Modal title={t("日志详情" )}
            open={open} showMask={false}
            onClose={close}
            width={"500"}
            theme={theme}
            btnColor={token.colorPrimary}
            btnHoverColor={token.colorPrimaryHover}
        >
            {/* <Descriptions 
                    bordered
                        size={size == 'large'?'default':size}
                        column={{ xs: 1, sm: 2, md: 2, lg: 2, xl: 2, xxl: 2 }}
                        items={items}
                    /> */}
            {
                loading?(
                    <Skeleton active />
                ):(<Descriptions 
                    bordered
                        size={size == 'large'?'default':size}
                        // size={dsize}
                        column={{ xs: 1, sm: 2, md: 2, lg: 2, xl: 2, xxl: 2 }}
                        items={items}
                    />
                )
            }
        </Modal>
        
    </>
    // return <>detail</>
}
