// codebase/admin-vue3/src/pages/sys/history/HistoryList.vue
<template>
  <TableComponent
    :page-size="20"
    :query="query"
    :api-url="api.history.list"
    :width="pos?.width"
    :height="pos?.height"
    :on-select="onSelect"
    :columns="columns"
    :refresh="refresh"
  />
</template>

<script setup lang="ts">
import { inject, computed } from 'vue';
import { useTranslation } from '@/hooks/useTranslation';
import { api } from '@/utils/api';
import TableComponent from '@/components/TableComponent.vue';
import { computePx } from '@/utils/kit';
import { AdminHistory } from '@/utils/I18NNamespace';

const props = defineProps<{
  query: any;
  refresh?: { reset: boolean; tag: any };
}>();

const emit = defineEmits<{
  (e: 'select', rows: any[]): void;
}>();

const { t } = useTranslation(AdminHistory);

const columns : any[]= [
  { title: t('ID'), key: 'id', sort: true, ellipsis: true, width: 80, fixed: 'left' },
  { title: t('操作人'), key: 'username', sort: true, filter: true, ellipsis: true, width: 150 },
  { title: t('IP地址'), key: 'ipAddr', sort: true, filter: true, ellipsis: true, width: 150 },
  { title: t('操作类型'), key: 'type', sort: true, filter: true, width: 150 },
  { title: t('操作时间'), key: 'created', sort: true, filter: true, ellipsis: true, width: 200 },
  { title: t('请求参数'), key: 'remark', ellipsis: true, align: 'left', width: 200 },
];

const modalPos = inject<any>('modalContext', null);

const pos = computed(() => {
  if (modalPos?.value?.width && modalPos?.value?.height) {
    return {
      width: computePx(modalPos.value.width),
      height: computePx(modalPos.value.height, true) - 350
    };
  }
  return { width: undefined, height: undefined };
});

const onSelect = (rows: any[]) => {
  emit('select', rows);
};
</script>

// codebase/admin/src/pages/history/HistoryListComponent.tsx

import { TableComponent, TableColumnType } from '../../components';
import { api } from '../../common/api';

export type HistoryListComponentType = {
    query: any,
    onSelect: (rows: any[]) => void, 
    refresh?: {
        /**
         * 是否刷新到第一页，false: 刷新当前页, true: 刷新至第一页，默认false
         */
        reset: boolean, 
        /**
         *  刷新标识，与上一次刷新的值不一样即可，可以是任意值
         */
        tag: any, 
    }
}

export const HistoryListComponent : React.FC<HistoryListComponentType> = ({
    query,
    onSelect,
    refresh
}) => {
    const columns : TableColumnType[]= [
        {
            title: 'ID',
            key: 'id',
            sort: true,
            ellipsis: true,
            width: 80,
            fixed: 'left'
        },
        {
            title: '账号',
            key: 'username',
            sort: true,
            filter: true,
            ellipsis: true,
            width: 150
        },
        {
            title: 'IP',
            key: 'ipAddr',
            sort: true,
            filter: true,
            ellipsis: true,
            width: 150
        },
        {
            title: '操作类型',
            key: 'type',
            sort: true,
            filter: true,
            width: 150
        },
        {
            title: '创建时间',
            key: 'created',
            sort: true,
            filter: true,
            ellipsis: true,
            width: 200
        },
        {
            title: '参数',
            key: 'remark',
            ellipsis: true,
            align: 'left'
        },
    ];
    
    return <TableComponent pageSize={20} query={query} apiUrl={api.history.list} refresh={refresh}
        onSelect={onSelect}
        columns={columns}
    />
}
