// codebase/admin/src/pages/sys/dict/DictGroupEdit.tsx
import { Button, Divider, Form, Input, Space, Typography } from "antd";
import { AdminDict, DefaultNS } from "../../../common/I18NNamespace";
import { useRequest, useTranslation, useSelector } from "../../../hooks";
import { Modal } from "../../../components";
import { useEffect, useState } from "react";
import { api } from "../../../common/api";
import { CloseOutlined, SendOutlined } from "@ant-design/icons";
import { useShowResult } from "../../../hooks/useShowResult";


export type DictGroupEditFormType = {
    remark?: string,
    label?: string,
    code?: string,
}

export type DictGroupEditType = {
    group: DictGroupEditFormType,
    open: boolean,
    onClose: (dict?: DictGroupEditFormType) => void,
    title
}

/**
 * 编辑字典名（字典分类）
 */
export const DictGroupEdit: React.FC<DictGroupEditType> = ({
    group,
    open,
    onClose,
    title 
}) => {
    const {t} = useTranslation(AdminDict);
    const request = useRequest();
    const [visible, setVisible] = useState(true);
    const size = useSelector(state => state.themeConfig.componentSize);

    const [form] = Form.useForm();
    const showResult = useShowResult(AdminDict);

    const onModalClose = () => {
        setVisible(false);
        setTimeout(()=>{
            onClose(null);
        }, 500)
    }

    const onSubmit = () => {
        form.submit();
    } 

    // const onFinish: FormProps<PermissionFormType>['onFinish'] = (values) => {
    const onFinish = (values) => {

        // console.log(values);
        let data = values;
        if(group && values.code != group.code){
            data = {...data, oldCode: group.code}
        }

        // console.log(values);
        const create = async () => {
            let result = await request.post(
                api.dict.saveOrUpdateGroup,
                data
            );
            showResult.show(result);
            if(result.status){
                onClose(data);
            }
        }
        create();
    };

    useEffect(()=>{
        if(open && group){
            form.setFieldsValue(group);
        }
    }, []);

    if(open)
        return <Modal open={visible} onClose={onModalClose} title={title} width={400}
                showMask={false}
            > 
                <div style={{width:'100%'}}>
                    <div style={{padding: "0px 20px 10px 20px", margin: "0px auto"}}>
                        <Typography.Title level={4} style={{marginTop: 20, marginBottom: 20, textAlign: "center"}}>{title}</Typography.Title>
                        <Form form = {form} layout='horizontal'
                            onFinish={onFinish}
                            size={size}
                        >   
                            <Form.Item<DictGroupEditFormType> label={t("显示名")} name="label"
                                rules={[{ required: true, message: t('字典显示名不能为空') }]}
                            >
                                <Input></Input>
                            </Form.Item>
                            <Form.Item<DictGroupEditFormType> label={t("字典代码")} name="code"
                                rules={[{ required: true, message: t('字典代码不能为空') }]}
                            >
                                 <Input></Input>
                            </Form.Item>
                            <Form.Item<DictGroupEditFormType> label={t("备注")} name="remark">
                                 <Input.TextArea rows={2} count={{max: 64, show: true}}></Input.TextArea>
                            </Form.Item>
                        </Form>
                        <Divider />
                        <div style={{textAlign: 'right'}}>
                            <Space>
                                <Button onClick={onModalClose} icon={<CloseOutlined />}>{t("取消", DefaultNS)}</Button>
                                <Button onClick={onSubmit} type="primary" icon={<SendOutlined />}>{t("确定", DefaultNS)}</Button>
                            </Space>
                        </div>
                    </div>
                </div>
            </Modal>
    else {
        return <></>
    }
}

// codebase/admin-vue3/src/pages/sys/dict/DictGroupEdit.vue
<template>
  <Modal
    :open="visible"
    :title="title"
    :width="400"
    :show-mask="false"
    @close="onModalClose"
  >
    <div style="width: 100%">
      <div style="padding: 0px 20px 10px 20px; margin: 0px auto">
        <h4 style="margin-top: 20px; margin-bottom: 20px; text-align: center;">{{ title }}</h4>
        
        <t-form ref="formRef" :data="formData" layout="horizontal" :rules="rules" @submit="onFinish">
          <t-form-item name="label" :label="t('显示名')">
            <t-input v-model="formData.label"></t-input>
          </t-form-item>
          
          <t-form-item name="code" :label="t('字典代码')">
            <t-input v-model="formData.code"></t-input>
          </t-form-item>
          
          <t-form-item name="remark" :label="t('备注')">
            <t-textarea v-model="formData.remark" :maxlength="64" />
          </t-form-item>
        </t-form>
        
        <t-divider />
        
        <div style="text-align: right">
          <t-space>
            <t-button variant="outline" @click="onModalClose">{{ t('取消') }}</t-button>
            <t-button theme="primary" @click="onSubmit">{{ t('确定') }}</t-button>
          </t-space>
        </div>
      </div>
    </div>
  </Modal>
</template>

<script setup lang="ts">
import { ref, reactive, watch, onMounted } from 'vue';
import Modal from '@/components/Modal/index.vue';
import { useTranslation } from '@/hooks/useTranslation';
import { useRequest } from '@/hooks/useRequest';
import { useShowResult } from '@/hooks/useShowResult';
import { api } from '@/utils/api';
import type { SubmitContext } from 'tdesign-vue-next';
import { AdminDict } from '@/utils/I18NNamespace';

interface DictGroupEditFormType {
  remark?: string;
  label?: string;
  code?: string;
}

const props = defineProps<{
  group?: DictGroupEditFormType | null;
  open: boolean;
  title: string;
}>();

const emit = defineEmits<{
  (e: 'close', dict?: DictGroupEditFormType | null): void;
  (e: 'update:open', val: boolean): void;
}>();

const { t } = useTranslation(AdminDict);
const request = useRequest();
const showResult = useShowResult(AdminDict);

const visible = ref(props.open);
const formRef = ref<any>(null);

const formData = reactive<DictGroupEditFormType>({
  label: '',
  code: '',
  remark: ''
});

const rules = {
  label: [{ required: true, message: t('字典显示名不能为空') }],
  code: [{ required: true, message: t('字典代码不能为空') }]
};

onMounted(() => {
  if (props.open && props.group) {
    Object.assign(formData, props.group);
  }
});

watch(() => props.open, (val) => {
  visible.value = val;
});

const onModalClose = () => {
  visible.value = false;
  emit('update:open', false);
  setTimeout(() => {
    emit('close', null);
  }, 500);
};

const onSubmit = () => {
  formRef.value.submit();
};

const onFinish = async ({ validateResult, firstError }: SubmitContext) => {
  if (validateResult === true) {
    let data: any = { ...formData };
    if (props.group && formData.code !== props.group.code) {
      data = { ...data, oldCode: props.group.code };
    }
    
    const result = await request.post(api.dict.saveOrUpdateGroup, data);
    showResult.show(result);
    
    if (result.status) {
      visible.value = false;
      emit('update:open', false);
      setTimeout(() => {
        emit('close', data);
      }, 500);
    }
  }
};
</script>
