// codebase/admin/src/pages/role/RoleEdit.tsx
import { useEffect, useState } from "react"
import { Modal, useRequest, useTranslation } from "../../components"
import { Button, Divider, Form, Input, Space, Typography, FormProps, App } from "antd"
import { useSelector } from "../../redux/hooks"
import { CloseOutlined, SendOutlined } from "@ant-design/icons"
import { RoleTypeSelector } from "./RoleType"
import { api } from "../../common/api"
import { AdminRole, DefaultNS } from "../../common/I18NNamespace"

export type RoleFormType = {
    id?: number | string,
    roleName?: string, 
    code?: string,
    type?: string[]
}

export type RoleAddType = {
    open: boolean,
    onClose: (refresh:boolean) => void,
    role?: any
}   

/**
 * 添加，编辑角色
 * @returns 
 */
export const RoleEdit : React.FC<RoleAddType> = ({
    open,
    onClose, 
    role
}) => {
    const [defaultValues, setDefaultValues] = useState<RoleFormType>();

    // if(role && !defaultValues){
    //     setDefaultValues({
    //         roleName: role.roleName,
    //         type: [role.type],
    //         code: role.code,
    //         id: role.id,
    //     })
    // }

    const {t} = useTranslation(AdminRole);
    const request = useRequest();
    const {message} = App.useApp();
    // const [visible, setVisible] = useState(open);
    const [form] = Form.useForm();

    const onModalClose = () => {
        // setVisible(false);
        onClose(false);
    }

    const onSubmit = () => {
        form.submit();
    } 

    const onFinish: FormProps<RoleFormType>['onFinish'] = (values) => {

        let data = values as any;
        data.type = data.type * 1;

        // console.log(values);
        const create = async () => {
            let result = await request.post(
                data.id?api.role.update:api.role.create,
                data
            );
            if(result.status){
                message.success(result.msg);
                onClose(true);
            }else{
                message.error(result.msg);
            }
        }
        create();
    };
    
    useEffect(()=>{
        if(role) {
            let values = {
                roleName: role.roleName,
                type: [role.type],
                code: role.code,
                id: role.id,
            };
            setDefaultValues(values)
            form.setFieldsValue(values);
        }else if(open){
            setDefaultValues(null);
            form.resetFields();
        }
    }, [open]);

    if(open) {
        return <Modal open={open} onClose={onModalClose} title={t("添加角色")} width={400}>
            <>
                <div style={{width:'100%'}}>
                    <div style={{padding: "0px 20px 10px 20px", width: 340, margin: "0px auto"}}>
                        <Typography.Title level={4} style={{marginTop: 20, marginBottom: 20, textAlign: "center"}}>{t("添加角色")}</Typography.Title>
                        <Form<RoleFormType> form = {form} layout='horizontal'
                            onFinish={onFinish}
                        >   
                            <Form.Item name="id" hidden={true}>
                                <Input></Input>
                            </Form.Item>
                            <Form.Item<RoleFormType> label={t("角色名")} name="roleName"
                                rules={[{ required: true, message: t('角色名不能为空') }]}
                            >
                                <Input></Input>
                            </Form.Item>
                            <Form.Item<RoleFormType> label={t("角色代码")} name="code"
                                rules={[{ required: true, message: t('角色代码不能为空') }]}
                            >
                                <Input></Input>
                            </Form.Item>
                            <Form.Item<RoleFormType> label={t("角色类型")} name="type"
                                rules={[{ required: true, message: t('角色类型不能为空') }]}
                            >
                                <RoleTypeSelector/>
                            </Form.Item>
                        </Form>
                        <Divider />
                        <div style={{textAlign: 'right'}}>
                            <Space>
                                <Button onClick={onModalClose} icon={<CloseOutlined />}>{t("取消", DefaultNS)}</Button>
                                <Button onClick={onSubmit} type="primary" icon={<SendOutlined />}>{t("确定", DefaultNS)}</Button>
                            </Space>
                        </div>
                    </div>
                </div>
            </>
        </Modal>
    }else {
        return <></>
    }
}

// codebase/admin-vue3/src/pages/sys/role/RoleEdit.vue
<template>
  <Modal
    :open="visible"
    :title="t('添加角色')"
    :width="400"
    :show-mask="false"
    @close="onModalClose(false)"
  >
    <div style="width: 100%">
      <div style="padding: 0px 20px 10px 20px; width: 340px; margin: 0px auto">
        <h4 style="margin-top: 20px; margin-bottom: 20px; text-align: center;">{{ t('添加角色') }}</h4>
        
        <t-form ref="formRef" :data="formData" layout="horizontal" :rules="rules" @submit="onFinish">
          <t-form-item name="roleName" :label="t('角色名')">
            <t-input v-model="formData.roleName" clearable></t-input>
          </t-form-item>
          
          <t-form-item name="code" :label="t('角色代码')">
            <t-input v-model="formData.code" clearable></t-input>
          </t-form-item>
          
          <t-form-item name="type" :label="t('角色类型')">
            <RoleTypeSelector v-model="formData.type" />
          </t-form-item>
        </t-form>
        
        <t-divider />
        
        <div style="text-align: right">
          <t-space>
            <t-button variant="outline" @click="onModalClose(false)">
              <template #icon><t-icon name="close" /></template>
              {{ t('取消') }}
            </t-button>
            <t-button theme="primary" @click="onSubmit">
              <template #icon><t-icon name="send" /></template>
              {{ t('确定') }}
            </t-button>
          </t-space>
        </div>
      </div>
    </div>
  </Modal>
</template>

<script setup lang="ts">
import { ref, reactive, watch, onMounted } from 'vue';
import Modal from '@/components/Modal/index.vue';
import { useTranslation } from '@/hooks/useTranslation';
import { useRequest } from '@/hooks/useRequest';
import { useShowResult } from '@/hooks/useShowResult';
import { api } from '@/utils/api';
import { RoleTypeSelector } from './RoleType';
import type { SubmitContext } from 'tdesign-vue-next';
import { AdminRole } from '@/utils/I18NNamespace';

interface RoleFormType {
  id?: number | string | null;
  roleName?: string;
  code?: string;
  type?: any;
}

const props = defineProps<{
  role?: RoleFormType | null;
  open: boolean;
}>();

const emit = defineEmits<{
  (e: 'close', refresh: boolean): void;
  (e: 'update:open', val: boolean): void;
}>();

const { t } = useTranslation(AdminRole);
const request = useRequest();
const showResult = useShowResult(AdminRole);

const visible = ref(props.open);
const formRef = ref<any>(null);

const formData = reactive<RoleFormType>({
  id: null,
  roleName: '',
  code: '',
  type: undefined
});

const rules = {
  roleName: [{ required: true, message: t('角色名不能为空') }],
  code: [{ required: true, message: t('角色代码不能为空') }],
  type: [{ required: true, message: t('角色类型不能为空') }]
};

onMounted(() => {
  if (props.open && props.role) {
    Object.assign(formData, {
      id: props.role.id,
      roleName: props.role.roleName,
      code: props.role.code,
      type: props.role.type
    });
  } else if (props.open) {
    formData.id = null;
    formData.roleName = '';
    formData.code = '';
    formData.type = undefined;
  }
});

watch(() => props.open, (val) => {
  visible.value = val;
  if (val && props.role) {
    Object.assign(formData, {
      id: props.role.id,
      roleName: props.role.roleName,
      code: props.role.code,
      type: props.role.type
    });
  } else if (val) {
    formData.id = null;
    formData.roleName = '';
    formData.code = '';
    formData.type = undefined;
  }
});

const onModalClose = (refresh: boolean) => {
  visible.value = false;
  emit('update:open', false);
  emit('close', refresh);
};

const onSubmit = () => {
  formRef.value.submit();
};

const onFinish = async ({ validateResult, firstError }: SubmitContext) => {
  if (validateResult === true) {
    const data: any = { ...formData };
    data.type = Number(data.type);
    
    const url = data.id ? api.role.update : api.role.create;
    
    const result = await request.post(url, data);
    showResult.show(result);
    
    if (result.status) {
      onModalClose(true);
    }
  }
};
</script>
