// codebase/admin-vue3/src/pages/sys/role/RoleQuery.vue
<template>
  <QueryComponent :items="queryItems" @query="onQueryEvent" />
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useTranslation } from '@/hooks/useTranslation';
import QueryComponent from '@/components/QueryComponent.vue';
import UserSelector from '../user/UserSelector.vue';
import { RoleTypeSelector } from './RoleType';
import { AdminRole } from '@/utils/I18NNamespace';

const emit = defineEmits<{
  (e: 'query', values: any): void;
}>();

const { t } = useTranslation(AdminRole);

const queryItems = computed(() => [
  { label: t('角色名'), name: 'userId', component: UserSelector, props: { mode: 'single', clearable: true } },
  { label: t('角色代码'), name: 'code', component: 't-input', props: { clearable: true } },
  { label: t('角色类型'), name: 'types', component: RoleTypeSelector, props: { clearable: true } },
  { label: t('创建人'), name: 'creaters', component: UserSelector, props: { mode: 'multiple', clearable: true } },
]);

const onQueryEvent = (values: any) => {
  const v: any = { ...values };

  if (v.types !== undefined && v.types !== null && v.types !== '') {
    v.types = [Number(v.types)];
  }

  if (v.creaters) {
    v.creaters = Array.isArray(v.creaters) ? v.creaters.map((x: any) => Number(x)) : [Number(v.creaters)];
  }

  if (v.userId !== undefined && v.userId !== null && v.userId !== '') {
    v.userId = Number(v.userId);
  }

  emit('query', v);
};
</script>

// codebase/admin/src/pages/sys/role/RoleQuery.tsx
import { useSelector, useTranslation } from '../../../hooks';
import { QueryComponent } from '../../../components';
import { Input } from "antd"
import { UserSelector } from '../user/index';
import { AdminRole } from '../../../common/I18NNamespace';


export type RoleQueryType = {
    onQuery: (values) => void         //点击查询后，获取到的字段集合
}

/**
 * 角色搜索条件表单
 * @returns 
 */
export const RoleQuery: React.FC<RoleQueryType> = ({onQuery}) => {

    const size = useSelector(state => state.themeConfig.componentSize);
    const {t} = useTranslation(AdminRole);

    const queryItems = [
        {
            label: t("角色名"),
            name: "userId",
            inputElement: <UserSelector name="userId" mode='single' size={size} allowClear/>
        },
        {
            label: t("角色代码"),
            name: "code",
            inputElement: <Input name="code" size={size} allowClear/>
        },
        {
            label: t("角色类型"),
            name: "types",
            inputElement: <Input name="types" size={size} allowClear/>
        },
        {
            label: t("创建人"),
            name: "creaters",
            inputElement: <UserSelector name="creaters" mode='multiple' size={size} allowClear/>
        }
    ]

    let onQueryEvent = (values) => {

        if(values.types){
            // [{"label": "普通管理员(admin)", "value": "3", "key": "3"}]
            values.types = values.types.map(item => item.value*1);
        }
        if(values.creaters){
            // [{"label": "普通管理员(admin)", "value": "3", "key": "3"}]
            values.creaters = values.creaters.map(item => item.value*1);
        }

        onQuery(values);
    }

    return <>
        <QueryComponent items={queryItems} onQuery={onQueryEvent} />
    </>
}
