// codebase/admin-vue3/src/pages/sys/role/RoleList.vue
<template>
  <TableComponent
    :page-size="20"
    :query="query"
    :api-url="api.role.list"
    :width="pos?.width"
    :height="pos?.height"
    :on-select="onSelect"
    :columns="columns"
    :refresh="refresh"
  />
</template>


<script setup lang="ts">
import { h, inject, computed } from 'vue';
import { useTranslation } from '@/hooks/useTranslation';
import { api } from '@/utils/api';
import TableComponent from '@/components/TableComponent.vue';
import { RoleTypeTag } from './RoleType';
import { computePx } from '@/utils/kit';
import { AdminRole } from '@/utils/I18NNamespace';

const props = defineProps<{
  query: any;
  refresh?: { reset: boolean; tag: any };
}>();

const emit = defineEmits<{
  (e: 'select', rows: any[]): void;
}>();

const { t } = useTranslation(AdminRole);

const columns : any[]= [
  { title: t('ID'), key: 'id', sort: true, ellipsis: true, width: 100 },
  { title: t('角色名'), key: 'roleName', sort: true, filter: true, ellipsis: true, width: 150 },
  { title: t('角色代码'), key: 'code', sort: true, filter: true, ellipsis: true, width: 200 },
  { 
    title: t('角色类型'), 
    key: 'type', 
    sort: true, 
    filter: true, 
    ellipsis: true, 
    width: 150,
    render: (text: any) => h(RoleTypeTag, { value: text }),
  },
  { title: t('创建人'), key: 'createrName', sort: true, filter: true, ellipsis: true, width: 150 },
];

const modalPos = inject<any>('modalContext', null);

const pos = computed(() => {
  if (modalPos?.value?.width && modalPos?.value?.height) {
    return {
      width: computePx(modalPos.value.width),
      height: computePx(modalPos.value.height, true) - 350
    };
  }
  return { width: undefined, height: undefined };
});

const onSelect = (rows: any[]) => {
  emit('select', rows);
};
</script>

// codebase/admin/src/pages/sys/role/RoleList.tsx

import { useTranslation } from '../../../hooks';
import { TableComponent, TableColumnType, ModalContext } from '../../../components';
import { api } from '../../../common/api';
import { RoleTypeTag } from './RoleType';
import { useContext, useEffect, useState } from 'react';
import { computePx } from '../../../common/kit';
import { AdminRole } from '../../../common/I18NNamespace';

export type RoleListType = {
    query: any,
    onSelect: (rows: any[]) => void,
    refresh?: {
        /**
         * 是否刷新到第一页，false: 刷新当前页, true: 刷新至第一页，默认false
         */
        reset: boolean, 
        /**
         *  刷新标识，与上一次刷新的值不一样即可，可以是任意值
         */
        tag: any, 
    }
}

/**
 * 角色列表组件
 * @returns 
 */
export const RoleList : React.FC<RoleListType> = ({
    query,
    onSelect,
    refresh
}) => {

    const {t} = useTranslation(AdminRole);

    const columns : TableColumnType[]= [
        {
            title: t('ID'),
            key: 'id',
            sort: true,
            ellipsis: true,
            width: 100
        },
        {
            title: t('角色名'),
            key: 'roleName',
            sort: true,
            filter: true,
            ellipsis: true,
            width: 150
        },
        {
            title: t('角色代码'),
            key: 'code',
            sort: true,
            filter: true,
            ellipsis: true,
            width: 200
        },
        {
            title: t('角色类型'),
            key: 'type',
            sort: true,
            filter: true,
            ellipsis: true,
            width: 150,
            render(text, record, index) {
                return <RoleTypeTag>{text}</RoleTypeTag>
            },
        },
        {
            title: t('创建人'),
            key: 'createrName',
            sort: true,
            filter: true,
            ellipsis: true,
            width: 150
        }
    ];
    
    //当组件使用窗口话的时候，获取窗口的位置信息，设置到表格
    const modalPos = useContext(ModalContext);
    const [pos, setPos] = useState({
        width: null, 
        height: null,
    });

    useEffect(()=> {
        if(modalPos && modalPos.width && modalPos.height){
            let npos = {
                width: computePx(modalPos.width),
                height: computePx(modalPos.height, true) - 350
            };
            // console.log(modalPos, npos);
            setPos(npos)
        }

    }, [modalPos]);

    return <TableComponent pageSize={20} query={query} apiUrl={api.role.list} 
        width={pos?.width} height={pos?.height}
        onSelect={onSelect}
        columns={columns}
        refresh={refresh}
    />
}
