// codebase/admin-vue3/src/pages/sys/role/RoleGrantPermission.vue
<template>
  <Modal
    :open="visible"
    :title="t('分配权限')"
    :width="900"
    :height="800"
    @close="onCloseModal"
  >
    <div style="padding: 0px 20px 10px 20px;">
      <h4 style="margin-top: 20px; margin-bottom: 20px; text-align: center;">{{ t('分配权限') }}</h4>
      
      <div style="height: 500px;">
        <t-transfer
          v-model="targetKeys"
          :data="permissions"
          :keys="{ label: 'name', value: 'key' }"
          :search="true"
          :title="[t('未分配'), t('已分配')]"
        >
          <template #title="{ type }">
            <template v-if="type === 'source'">
              {{ t('未分配') }}
            </template>
            <template v-else>
              {{ t('已分配') }}
            </template>
          </template>
          <!-- Using standard transfer since table transfer is complex in TDesign Vue -->
          <template #default="{ data }">
            <div style="display: flex; justify-content: space-between; width: 100%;">
              <span>{{ data.name }}</span>
              <t-tag theme="primary" variant="light" size="small">{{ data.groupName }}</t-tag>
            </div>
          </template>
        </t-transfer>
      </div>
      
      <t-divider />
      
      <div style="text-align: right;">
        <t-button variant="outline" @click="onClickCancel">{{ t('取消') }}</t-button>
        <t-button theme="primary" style="margin-left: 20px;" @click="onClickOk">{{ t('确定') }}</t-button>
      </div>
    </div>
  </Modal>
</template>

<script setup lang="ts">
import { ref, onMounted, watch } from 'vue';
import Modal from '@/components/Modal/index.vue';
import { useTranslation } from '@/hooks/useTranslation';
import { useRequest } from '@/hooks/useRequest';
import { useShowResult } from '@/hooks/useShowResult';
import { api } from '@/utils/api';
import { AdminRole } from '@/utils/I18NNamespace';

const props = defineProps<{
  roleId: number;
  open: boolean;
}>();

const emit = defineEmits<{
  (e: 'close'): void;
  (e: 'update:open', val: boolean): void;
}>();

const { t } = useTranslation(AdminRole);
const request = useRequest();
const showResult = useShowResult(AdminRole);

const visible = ref(props.open);
const permissions = ref<any[]>([]);
const targetKeys = ref<any[]>([]);

watch(() => props.open, (val) => {
  visible.value = val;
});

const getAll = async () => {
  const result = await request.get(api.permission.curr);
  if (result && result.data) {
    permissions.value = result.data.map((p: any) => ({
      key: p.id,
      name: p.name,
      groupName: p.groupName,
      expression: p.expression
    }));
  }
};

const getSelectKeys = async () => {
  const result = await request.get(`${api.permission.byRole}?id=${props.roleId}`);
  if (result && result.data) {
    targetKeys.value = result.data.map((p: any) => p.id);
  }
};

onMounted(() => {
  getAll();
  getSelectKeys();
});

const onCloseModal = () => {
  visible.value = false;
  emit('update:open', false);
  setTimeout(() => {
    emit('close');
  }, 500);
};

const onClickCancel = () => {
  onCloseModal();
};

const onClickOk = async () => {
  const result = await request.post(`${api.role.grantPermissions}?id=${props.roleId}`, targetKeys.value);
  showResult.show(result);
  if (result.status) {
    onCloseModal();
  }
};
</script>

<style scoped>
:deep(.t-transfer) {
  height: 100%;
}
:deep(.t-transfer__list) {
  height: 100%;
}
</style>

// codebase/admin/src/pages/sys/role/RoleGrantPermission.tsx
import React, { useContext, useEffect, useState } from 'react';
import { Button, Divider, Flex, Table, Tag, Tooltip, Transfer, Typography } from 'antd';
import type { GetProp, TableColumnsType, TableProps, TransferProps } from 'antd';
import { useRequest, useShowResult, useTranslation } from '../../../hooks';
import { Modal, ModalContext } from '../../../components';
import { AdminRole } from '../../../common/I18NNamespace';
import { computePx } from '../../../common/kit';
import { api } from '../../../common/api';

type TransferItem = GetProp<TransferProps, 'dataSource'>[number];
type TableRowSelection<T extends object> = TableProps<T>['rowSelection'];

interface DataType {
    key: number;
    name: string;
    expression: string;
    groupName: string;
}

interface TableTransferProps extends TransferProps<TransferItem> {
    dataSource: DataType[];
    leftColumns: TableColumnsType<DataType>;
    rightColumns: TableColumnsType<DataType>;
}

// Customize Table Transfer
const TableTransfer: React.FC<TableTransferProps> = (props) => {
    const { leftColumns, rightColumns, ...restProps } = props;

    //当组件使用窗口话的时候，获取窗口的位置信息，设置到表格
    const modalPos = useContext(ModalContext);
    const [pos, setPos] = useState({
        width: null, 
        height: null,
    });

    useEffect(()=> {
        if(modalPos && modalPos.width && modalPos.height){
            let npos = {
                width: computePx(modalPos.width),
                height: computePx(modalPos.height, true) 
            };
            // console.log(modalPos, npos);
            setPos(npos)
        }

    }, [modalPos]);

    return (
        <Transfer style={{ width: '100%' }} {...restProps}>
            {({
                direction,
                filteredItems,
                onItemSelect,
                onItemSelectAll,
                selectedKeys: listSelectedKeys,
            }) => {
                const columns = direction === 'left' ? leftColumns : rightColumns;
                const rowSelection: TableRowSelection<TransferItem> = {
                    onChange(selectedRowKeys) {
                        onItemSelectAll(selectedRowKeys, 'replace');
                    },
                    selectedRowKeys: listSelectedKeys,
                    selections: [Table.SELECTION_ALL, Table.SELECTION_INVERT, Table.SELECTION_NONE],
                };

                return (
                    <Table
                        rowSelection={rowSelection}
                        columns={columns}
                        dataSource={filteredItems}
                        pagination={{
                            pageSize: 10000
                        }}
                        scroll={{y: pos.height? pos.height - 350 : 500}}
                        onRow={({ key }) => ({
                            onClick: () => {
                                onItemSelect(key, !listSelectedKeys.includes(key));
                            },
                        })}
                        rowKey={(record) => record.key}
                        size="small"
                    />
                );
            }}
        </Transfer>
    );
};

//权限列表类型定义
const columns: TableColumnsType<DataType> = [
    {
        dataIndex: 'name',
        title: '权限名',
        sorter: (a, b) => a.name.localeCompare(b.name),
        sortDirections: ['descend', 'ascend'],
    },
    {
        dataIndex: 'expression',
        title: '表达式',
        ellipsis: true,
        sorter: (a, b) => a.name.localeCompare(b.name),
        sortDirections: ['descend', 'ascend'],
        render(text, record, index) {
            return <Tooltip title={text}>
                 {text}
            </Tooltip>
        },
    },
    {
        dataIndex: 'groupName',
        title: '分组',
        sorter: (a, b) => a.name.localeCompare(b.name),
        sortDirections: ['descend', 'ascend'],
        render: (groupName: string) => (
            <Tag style={{ marginInlineEnd: 0 }} color="cyan">
                {groupName}
            </Tag>
        ),
    },
];

const filterOption = (input: string, item: DataType) => 
    item.name?.includes(input) || item.groupName?.includes(input) || item.expression.includes(input);

/**
 * 分配权限页面
 */
export const RoleGrantPermisison: React.FC<{
    roleId: number,
    onClose: () => void
}> = ({
    roleId,
    onClose
}) => {
    const [targetKeys, setTargetKeys] = useState<TransferProps['targetKeys']>([]);

    const {t} = useTranslation(AdminRole);
    const request = useRequest();
    const [permissions, setPermissions] = useState<DataType[]>([]);
    const showResult = useShowResult(AdminRole);

    const getAll = async () => {
        let result = await request.get(api.permission.curr);
        if(result){
            setPermissions(result.data.map(p => ({
                key: p.id,
                name: p.name,
                groupName: p.groupName,
                expression: p.expression
            })));
        }
    }

    //获取已分配的权限
    const getSelectKeys = async () => {
        let result = await request.get(api.permission.byRole+"?id="+roleId);
        if(result){
            // console.log(result.data.map(p => p.id));
            setTargetKeys(result.data.map(p => p.id))
        }
    }

    useEffect(()=>{
        getAll();
        getSelectKeys();
    }, []);

    //移动事件回调
    const onChange: TableTransferProps['onChange'] = (nextTargetKeys) => {
        // console.log(nextTargetKeys);
        setTargetKeys(nextTargetKeys);
    };

    const [visible, setVisible] = useState(true);

    const onCloseModal = () => {
        setVisible(false);
        setTimeout(() => {
            onClose();
        }, 500);
    }

    const onClickCancel = () => {
        onCloseModal();
    }

    //提交分配结果
    const onClickOk = async () => {
        // console.log(targetKeys);
        let result = await request.post(api.role.grantRolePermissions+"?id="+roleId, targetKeys);
        showResult.show(result);
    }

    return (
        <Modal width={900} height={800} open={visible} onClose={onCloseModal} 
            title={t("分配权限")}
        >
            <div style={{padding: "0px 20px 10px 20px"}}>
                <Typography.Title level={4} style={{marginTop: 20, marginBottom: 20, textAlign: "center"}}>{t('分配权限')}</Typography.Title>
                <Flex align="start" gap="middle" vertical>
                    <TableTransfer
                        dataSource={permissions}
                        targetKeys={targetKeys}
                        showSearch
                        showSelectAll={false}
                        onChange={onChange}
                        filterOption={filterOption}
                        leftColumns={columns}
                        rightColumns={columns}
                    />
                </Flex>
                <Divider />
                <div style={{
                    textAlign: "right",
                }}>
                    <Button onClick={onClickCancel}>{t('取消')}</Button>
                    <Button onClick={onClickOk} type="primary" style={{
                        marginLeft: 20
                    }}>{t('确定')}</Button>
                </div>
            </div>
        </Modal>
    );
};
