// codebase/admin/src/pages/sys/document/DocumentList.tsx

import { useTranslation } from '../../../hooks';
import { TableComponent, TableColumnType, ModalContext } from '../../../components';
import { api } from '../../../common/api';
import { useContext, useEffect, useState } from 'react';
import { computePx } from '../../../common/kit';
import { AdminDocument } from '../../../common/I18NNamespace';
import { Image } from 'antd';

export type DocumentListType = {
    query: any,
    onSelect: (rows: any[]) => void,
    refresh?: {
        /**
         * 是否刷新到第一页，false: 刷新当前页, true: 刷新至第一页，默认false
         */
        reset: boolean, 
        /**
         *  刷新标识，与上一次刷新的值不一样即可，可以是任意值
         */
        tag: any, 
    }
}

/**
 * 文档列表组件
 * @returns 
 */
export const DocumentList : React.FC<DocumentListType> = ({
    query,
    onSelect,
    refresh,
}) => {

    const {t} = useTranslation(AdminDocument);

    const columns : TableColumnType[]= [
        {
            title: t('ID'),
            key: 'id',
            sort: true,
            ellipsis: true,
            width: 100
        },
        {
            title: t('缩略图'),
            key: 'id',
            sort: true,
            filter: true,
            ellipsis: true,
            width: 80,
            render(text, record, index) {

                let name = record.fileName.toLowerCase();
                if(name.endsWith(".jpg") || name.endsWith(".jpeg") || name.endsWith(".png") 
                    || name.endsWith(".") || name.endsWith(".webp") 
                ){
                    return <span><Image
                        width={45}
                        src={api.document.img+"?id="+text}
                    /></span>
                }else{
                    return <span></span>
                }
            },
        },
        {
            title: t('文件名'),
            key: 'fileName',
            sort: true,
            filter: true,
            ellipsis: true,
            width: 150
        },
        {
            title: t('文件路径'),
            key: 'path',
            sort: true,
            filter: true,
            ellipsis: true,
            width: 200
        },
        {
            title: t('类型'),
            key: 'type',
            sort: true,
            filter: true,
            ellipsis: true,
            width: 150,
        },
        {
            title: t('创建人'),
            key: 'createrName',
            sort: true,
            filter: true,
            ellipsis: true,
            width: 150
        },
        {
            title: t('创建时间'),
            key: 'created',
            sort: true,
            filter: true,
            ellipsis: true,
            width: 150
        },
        {
            title: t('备注'),
            key: 'remark',
            sort: true,
            filter: true,
            ellipsis: true,
            width: 150
        }
    ];
    
    //当组件使用窗口话的时候，获取窗口的位置信息，设置到表格
    const modalPos = useContext(ModalContext);
    const [pos, setPos] = useState({
        width: null, 
        height: null,
    });

    useEffect(()=> {
        if(modalPos && modalPos.width && modalPos.height){
            let npos = {
                width: computePx(modalPos.width),
                height: computePx(modalPos.height, true) - 350
            };
            // console.log(modalPos, npos);
            setPos(npos)
        }

    }, [modalPos]);

    return <TableComponent pageSize={20} query={query} apiUrl={api.document.list} 
        width={pos?.width} height={pos?.height}
        onSelect={onSelect}
        columns={columns}
        refresh={refresh}
    />
}

// codebase/admin-vue3/src/pages/sys/document/DocumentList.vue
<template>
  <TableComponent
    :page-size="20"
    :query="query"
    :api-url="api.document.list"
    :width="pos?.width"
    :height="pos?.height"
    :on-select="onSelect"
    :columns="columns"
    :refresh="refresh"
  />
</template>

<script setup lang="ts">
import { h, inject, computed } from 'vue';
import { useTranslation } from '@/hooks/useTranslation';
import { api } from '@/utils/api';
import TableComponent from '@/components/TableComponent.vue';
import { computePx } from '@/utils/kit';
import { AdminDocument } from '@/utils/I18NNamespace';

const props = defineProps<{
  query: any;
  refresh?: { reset: boolean; tag: any };
}>();

const emit = defineEmits<{
  (e: 'select', rows: any[]): void;
}>();

const { t } = useTranslation(AdminDocument);

const imgUrl = api.document?.img ;

const columns : any[] = [
  { title: t('ID'), key: 'id', sort: true, ellipsis: true, width: 100 },
  { 
    title: t('缩略图'), 
    key: 'thumb', 
    sort: false, 
    filter: false, 
    ellipsis: true, 
    width: 80,
    render: (text: any, record: any) => {
      const name = (record.fileName || '').toLowerCase();
      if (name.endsWith('.jpg') || name.endsWith('.jpeg') || name.endsWith('.png') || name.endsWith('.webp')) {
        return h('img', { 
          src: `${imgUrl}?id=${record.id}`, 
          style: { width: '45px', height: '45px', objectFit: 'cover' } 
        });
      }
      return h('span');
    }
  },
  { title: t('文件名'), key: 'fileName', sort: true, filter: "input", ellipsis: true, width: 150 },
  { title: t('文件路径'), key: 'path', sort: true, filter: "input", ellipsis: true, width: 200, align: 'left' },
  { title: t('类型'), key: 'type', sort: true, filter: "select", ellipsis: true, width: 150 },
  { title: t('创建人'), key: 'createrName', sort: true, filter: "input", ellipsis: true, width: 150 },
  { title: t('创建时间'), key: 'created', sort: true, filter: "datepicker", ellipsis: true, width: 150 },
  { title: t('备注'), key: 'remark', sort: true, filter: "input", ellipsis: true, width: 150 },
];

const modalPos = inject<any>('modalContext', null);

const pos = computed(() => {
  if (modalPos?.value?.width && modalPos?.value?.height) {
    return {
      width: computePx(modalPos.value.width),
      height: computePx(modalPos.value.height, true) - 350
    };
  }
  return { width: undefined, height: undefined };
});

const onSelect = (rows: any[]) => {
  emit('select', rows);
};
</script>
