// codebase/admin/src/pages/sys/document/DocumentQuery.tsx
import { QueryComponent } from '../../../components';
import { useTranslation,useSelector } from '../../../hooks';
import { Input, DatePicker } from "antd"
import { UserSelector } from '../user/index';
import { AdminDocument } from '../../../common/I18NNamespace';

const { RangePicker } = DatePicker;


export type DocumentQueryType = {
    onQuery: (values) => void         //点击查询后，获取到的字段集合
}

/**
 * 文件管理的搜索条件表单
 * @returns 
 */
export const DocumentQuery: React.FC<DocumentQueryType> = ({onQuery}) => {

    const size = useSelector(state => state.themeConfig.componentSize);
    const {t} = useTranslation(AdminDocument);

    const queryItems = [
        {
            label: t("文件名"),
            name: "name",
            inputElement: <Input name="name" size={size} allowClear/>
        },
        {
            label: t("创建人"),
            name: "creater",
            inputElement: <UserSelector name="creater" mode='single' size={size} allowClear/>
        },
        {
            label: t("文件类型"),
            name: "type",
            inputElement: <Input name="type" size={size} allowClear/>
        },
        {
            label: t("备注"),
            name: "remark",
            inputElement: <Input name="remark" size={size} allowClear/>
        },
        {
            label: t("创建时间"),
            name: "created",
            inputElement: <RangePicker name="created" size={size} allowClear/>
        }
    ]

    let onQueryEvent = (values) => {

        if(values.creater){
            // [{"label": "普通管理员(admin)", "value": "3", "key": "3"}]
            // console.log(values.creater);
            values.creater = values.creater[0].key * 1
        }

        if(values.created){
            let start = values.created[0].format("YYYY-MM-DD");
            let end = values.created[1].format("YYYY-MM-DD");
            // console.log(start, end);
            values['startDate'] = start;
            values['endDate'] = end;
            delete values.created
        }

        onQuery(values);
    }

    return <>
        <QueryComponent items={queryItems} onQuery={onQueryEvent} />
    </>
}

// codebase/admin-vue3/src/pages/sys/document/DocumentQuery.vue
<template>
    <QueryComponent :items="queryItems" @query="onQueryEvent" />
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useTranslation } from '@/hooks/useTranslation';
import QueryComponent from '@/components/QueryComponent.vue';
import UserSelector from '../user/UserSelector.vue';
import dayjs from 'dayjs';
import { AdminDocument } from '@/utils/I18NNamespace';

const emit = defineEmits<{
    (e: 'query', values: any): void;
}>();

const { t } = useTranslation(AdminDocument);

const queryItems = computed(() => [
    { label: t('文件名'), name: 'name', component: 't-input', props: { clearable: true } },
    { label: t('创建人'), name: 'creater', component: UserSelector, props: { mode: 'single', clearable: true } },
    { label: t('文件类型'), name: 'type', component: 't-input', props: { clearable: true } },
    { label: t('备注'), name: 'remark', component: 't-input', props: { clearable: true } },
    { label: t('创建时间'), name: 'created', component: 't-date-range-picker', props: { clearable: true, allowInput: true }, width: 360 },
]);

const onQueryEvent = (values: any) => {
    const v: any = { ...values };

    if (v.creater !== undefined && v.creater !== null && v.creater !== '') {
        v.creater = Number(v.creater);
    }

    if (v.created && Array.isArray(v.created) && v.created.length === 2) {
        v.startDate = dayjs(v.created[0]).format('YYYY-MM-DD');
        v.endDate = dayjs(v.created[1]).format('YYYY-MM-DD');
        delete v.created;
    }

    emit('query', v);
};
</script>
