// codebase/admin-vue3/src/pages/sys/lang/ResourceEdit.vue
<template>
  <Modal
    :open="visible"
    :title="t('编辑语言资源')"
    :width="500"
    :height="500"
    :show-mask="false"
    @close="onModalClose(false)"
  >
    <div style="width: 100%">
      <div style="padding: 0px 20px 10px 20px; margin: 0px auto">
        <h4 style="margin-top: 20px; margin-bottom: 20px; text-align: center;">{{ t('编辑语言资源') }}</h4>
        
        <t-form ref="formRef" :data="formData" layout="horizontal" :rules="rules" @submit="onFinish" label-align="left" :label-width="80">
          <t-form-item name="resKey" :label="t('KEY')">
            <t-input v-model="formData.resKey" :disabled="!!resource"></t-input>
          </t-form-item>
          
          <t-form-item v-if="!resource" name="category" :label="t('分组')">
            <t-auto-complete
              v-model="formData.category"
              :options="groupOptions"
              @change="onSearchGroups"
            />
          </t-form-item>
          
          <template v-for="(val, index) in formData.resValues" :key="index">
            <t-form-item :label="langs[index].code">
              <t-textarea v-model="val.resValue" :rows="2" :maxlength="255"></t-textarea>
            </t-form-item>
          </template>
        </t-form>
        
        <t-divider />
        
        <div style="text-align: right">
          <t-space>
            <t-button variant="outline" @click="onModalClose(false)">
              <template #icon><t-icon name="close" /></template>
              {{ t('取消') }}
            </t-button>
            <t-button theme="primary" @click="onSubmit">
              <template #icon><t-icon name="send" /></template>
              {{ t('确定') }}
            </t-button>
          </t-space>
        </div>
      </div>
    </div>
  </Modal>
</template>

<script setup lang="ts">
import { ref, reactive, watch, onMounted, computed } from 'vue';
import Modal from '@/components/Modal/index.vue';
import { useTranslation } from '@/hooks/useTranslation';
import { useRequest } from '@/hooks/useRequest';
import { useShowResult } from '@/hooks/useShowResult';
import { AdminLang } from '@/utils/I18NNamespace';
import { api } from '@/utils/api';
import type { SubmitContext } from 'tdesign-vue-next';

interface ResourceEditType {
  resource?: any;
  groups?: any[];
  langs: any[];
  open: boolean;
}

const props = defineProps<ResourceEditType>();

const emit = defineEmits<{
  (e: 'close', refresh: boolean): void;
  (e: 'update:open', val: boolean): void;
}>();

const { t } = useTranslation(AdminLang);
const request = useRequest();
const showResult = useShowResult(AdminLang);

const visible = ref(props.open);
const formRef = ref<any>(null);

const formData = reactive({
  resKey: '',
  category: '',
  resValues: [] as any[]
});

const rules = {
  resKey: [{ required: true, message: t('KEY不能为空') }],
  category: [{ required: true, message: t('分组不能为空') }]
};

const allGroupOptions = computed(() => {
  return (props.groups || []).map(g => ({
    label: g,
    value: g
  }));
});

const groupOptions = ref(allGroupOptions.value);

const onSearchGroups = (text: string) => {
  if (!text || /\s+/.test(text)) {
    groupOptions.value = allGroupOptions.value;
    return;
  }
  
  groupOptions.value = allGroupOptions.value.filter(g => 
    g.label.toLowerCase().includes(text.toLowerCase())
  );
};

const getResesAndBuildFormData = async () => {
  const result = await request.get(`${api.lang.resourceByKey}?id=${encodeURIComponent(props.resource.id)}`);
  if (result.status) {
    const reses = result.data;
    
    formData.resKey = props.resource.resKey;
    formData.category = props.resource.category;
    formData.resValues = [];

    props.langs.forEach(lang => {
      const res = reses.find((s: any) => s.languageId === lang.id);
      if (res) {
        formData.resValues.push({
          id: res.id,
          resValue: res.resValue,
          languageId: lang.id,
        });
      } else {
        formData.resValues.push({
          id: null,
          resValue: '',
          languageId: lang.id,
        });
      }
    });
  }
};

onMounted(() => {
  if (props.open && props.langs) {
    if (props.resource) {
      getResesAndBuildFormData();
    } else {
      formData.resKey = '';
      formData.category = '';
      formData.resValues = [];
      
      props.langs.forEach(lang => {
        formData.resValues.push({
          id: null,
          resValue: '',
          languageId: lang.id,
        });
      });
    }
  }
});

watch(() => props.open, (val) => {
  visible.value = val;
});

const onModalClose = (refresh: boolean) => {
  visible.value = false;
  emit('update:open', false);
  setTimeout(() => {
    emit('close', refresh);
  }, 300);
};

const onSubmit = () => {
  formRef.value.submit();
};

const onFinish = async ({ validateResult }: SubmitContext) => {
  if (validateResult === true) {
    const data = formData.resValues.map(v => ({
      ...v,
      resKey: formData.resKey,
      category: formData.category
    }));
    
    const result = await request.post(api.lang.updateRes, data);
    showResult.show(result);
    
    if (result.status) {
      onModalClose(true);
    }
  }
};
</script>

// codebase/admin/src/pages/sys/lang/ResourceEdit.tsx
import { AutoComplete, Button, Divider, Form, FormProps, Input, Space, Typography } from "antd";
import { AdminLang, DefaultNS } from "../../../common/I18NNamespace";
import { useRequest, useSelector, useTranslation } from "../../../hooks";
import { Modal } from "../../../components";
import { useEffect, useState } from "react";
import { api } from "../../../common/api";
import { CloseOutlined, SendOutlined } from "@ant-design/icons";
import { useShowResult } from "../../../hooks/useShowResult";

/**
 * 编辑语言资源的表单类型
 */
export type ResourceEditFormType = {
    resKey?: string,
    category?: string, 
    resValues?: {
        id?: number,
        resValue?: string,
        languageId?: number,
    }[]
}

/**
 * 编辑语言资源页面所需的数据类型
 */
export type ResourceEditType = {
    resource?: {
        id?: number,
        languageId?: string,
        category?: string,
        resKey?: string,
        resValue?: string
    },
    groups?: any[],
    langs: {
        id?: number,
        label?: string, 
        code?: string
    }[]
    open: boolean,
    onClose: (refresh) => void,
}

/**
 * 语言资源新增，编辑页面
 */
export const ResourceEdit: React.FC<ResourceEditType> = ({
    resource,
    langs,
    groups,
    open,
    onClose,
}) => {
    const {t} = useTranslation(AdminLang);
    const request = useRequest();
    const [visible, setVisible] = useState(true);
    const size = useSelector(state => state.themeConfig.componentSize);
    const [groupOptions, setGroupOptions] = useState<any[]>();
    const showResult = useShowResult(AdminLang);

    const [form] = Form.useForm();

    const onModalClose = (refresh) => {
        setVisible(false);
        setTimeout(()=>{
            onClose(refresh);
        }, 300)
    }

    const onSubmit = () => {
        form.submit();
    } 

    const onSearchGroups = (text) => {
        setGroupOptions(
            groups.filter(g => g.toLowerCase().indexOf(text.toLowerCase())>-1)
                .map(g => ({value: g}))
        )
    }

    //提交数据到后台
    const onFinish: FormProps<ResourceEditFormType>['onFinish'] = (values) => {
    // const onFinish = (values: ResourceEditFormType) => {
        // console.log(values);

        let data = [...values.resValues].map(v => ({...v, resKey: values.resKey, category: values.category}));
        // console.log(values);
        const create = async () => {
            let result = await request.post(
                api.lang.updateRes,
                data
            );
            showResult.show(result);
            if(result.status){
                onModalClose(true);
            }
        }
        create();
    };

    //获取相同key下面的所有数据
    const getResesAndBuildFormData = async () => {
        let result = await request.get(api.lang.resourceByKey+"?id="+encodeURIComponent(resource.id))
        if(result.status){
            let reses = result.data;
            let fd: ResourceEditFormType = {
                resKey: resource.resKey,
                category: resource.category,
                resValues: []    
            }

            langs.forEach(lang => {
                let res = reses.find(s => s.languageId == lang.id);
                if(res){
                    fd.resValues.push({
                        id: res.id,
                        resValue: res.resValue,
                        languageId: lang.id,
                    });
                }else{
                    fd.resValues.push({
                        id: null,
                        resValue: null,
                        languageId: lang.id,
                    });
                }
               
            })

            // setFormData(fd);
            form.setFieldsValue(fd);
        }
    }

    //监听数据变化，构建表单
    useEffect(()=>{
        if(groups){
            setGroupOptions(groups.map(g => ({value: g})))
        }

        if(open && langs){
            if(resource){
                getResesAndBuildFormData();
            }else{
                let fd: ResourceEditFormType = {
                    resKey: null,
                    category: null,
                    resValues: []    
                };
                langs.forEach(lang => {
                    fd.resValues.push({
                        id: null,
                        resValue: null,
                        languageId: lang.id,
                    });
                });
                form.setFieldsValue(fd);
            }
        }
    }, []);

    return <Modal open={visible} onClose={()=> onModalClose(false)} title={t("编辑语言资源")} width={500}
            showMask={false}
        > 
            <div style={{width:'100%'}}>
                <div style={{padding: "0px 20px 10px 20px", margin: "0px auto"}}>
                    <Typography.Title level={4} style={{marginTop: 20, marginBottom: 20, textAlign: "center"}}>{t("编辑语言资源")}</Typography.Title>
                    <Form<ResourceEditFormType> form = {form} layout='horizontal' 
                        onFinish={onFinish}  size={size}
                        labelCol={{span: 4}}
                    >   
                        <Form.Item<ResourceEditFormType> label={t("KEY")} name="resKey" 
                            rules={[{ required: true, message: t('KEY不能为空') }]}
                        >
                            <Input disabled={resource?true: false}></Input>
                        </Form.Item>
                        <Form.Item<ResourceEditFormType> label={t("分组")} name="category" 
                            rules={[{ required: true, message: t('分组不能为空') }]}
                            hidden={resource?true:false} noStyle={resource?true:false}
                        >
                            {resource?(<></>): 
                            <AutoComplete options={groupOptions}
                                onSearch={onSearchGroups}
                            />}
                        </Form.Item>
                        <Form.List name="resValues">
                            {(fields)=> fields.map(({ key, name, ...restField })=>(
                                <span key={key}>
                                    <Form.Item noStyle hidden name={[name, 'id']} {...restField}></Form.Item>
                                    <Form.Item noStyle hidden name={[name, 'category']} {...restField}></Form.Item>
                                    <Form.Item noStyle hidden name={[name, 'languageId']} {...restField}></Form.Item>
                                    <Form.Item label={langs[key].code} name={[name, "resValue"]} {...restField}>
                                        <Input.TextArea rows={2} count={{max: 255, show: true}}></Input.TextArea>
                                    </Form.Item>
                                </span>
                            ))}
                        </Form.List>
                    </Form>
                    <Divider />
                    <div style={{textAlign: 'right'}}>
                        <Space>
                            <Button onClick={()=>onModalClose(false)} icon={<CloseOutlined />}>{t("取消", DefaultNS)}</Button>
                            <Button onClick={onSubmit} type="primary" icon={<SendOutlined />}>{t("确定", DefaultNS)}</Button>
                        </Space>
                    </div>
                </div>
            </div>
        </Modal>
    
}
