// codebase/admin-vue3/src/pages/sys/permission/PermissionEdit.vue
<template>
  <Modal
    :open="visible"
    :title="title"
    :width="400"
    :show-mask="false"
    @close="onModalClose(false)"
  >
    <div style="width: 100%">
      <div style="padding: 0px 20px 10px 20px; width: 340px; margin: 0px auto">
        <h4 style="margin-top: 20px; margin-bottom: 20px; text-align: center;">{{ title }}</h4>
        
        <t-form ref="formRef" :data="formData" layout="horizontal" :rules="rules" @submit="onFinish">
          <t-form-item name="groupName" :label="t('分组名')">
            <t-input v-model="formData.groupName" clearable></t-input>
          </t-form-item>
          
          <t-form-item name="name" :label="t('权限名')">
            <t-input v-model="formData.name" clearable></t-input>
          </t-form-item>
          
          <t-form-item name="expression" :label="t('表达式')">
            <t-input v-model="formData.expression" clearable></t-input>
          </t-form-item>
        </t-form>
        
        <t-divider />
        
        <div style="text-align: right">
          <t-space>
            <t-button variant="outline" @click="onModalClose(false)">
              <template #icon><t-icon name="close" /></template>
              {{ t('取消') }}
            </t-button>
            <t-button theme="primary" @click="onSubmit">
              <template #icon><t-icon name="send" /></template>
              {{ t('确定') }}
            </t-button>
          </t-space>
        </div>
      </div>
    </div>
  </Modal>
</template>

<script setup lang="ts">
import { ref, reactive, watch, onMounted } from 'vue';
import Modal from '@/components/Modal/index.vue';
import { useTranslation } from '@/hooks/useTranslation';
import { useRequest } from '@/hooks/useRequest';
import { useShowResult } from '@/hooks/useShowResult';
import { api } from '@/utils/api';
import type { SubmitContext } from 'tdesign-vue-next';
import { AdminPermission } from '@/utils/I18NNamespace';

interface PermissionFormType {
  id?: number | string | null;
  groupName?: string;
  name?: string;
  expression?: string;
}

const props = defineProps<{
  permission?: PermissionFormType | null;
  title: string;
  open: boolean;
}>();

const emit = defineEmits<{
  (e: 'close', refresh: boolean): void;
  (e: 'update:open', val: boolean): void;
}>();

const { t } = useTranslation(AdminPermission);
const request = useRequest();
const showResult = useShowResult(AdminPermission);

const visible = ref(props.open);
const formRef = ref<any>(null);

const formData = reactive<PermissionFormType>({
  id: null,
  groupName: '',
  name: '',
  expression: ''
});

const rules = {
  groupName: [{ required: true, message: t('分组名不能为空') }],
  name: [{ required: true, message: t('权限名不能为空') }],
  expression: [{ required: true, message: t('表达式不能为空') }]
};

onMounted(() => {
  if (props.open && props.permission) {
    Object.assign(formData, {
      id: props.permission.id,
      groupName: props.permission.groupName,
      name: props.permission.name,
      expression: props.permission.expression
    });
  } else if (props.open) {
    formData.id = null;
    formData.groupName = '';
    formData.name = '';
    formData.expression = '';
  }
});

watch(() => props.open, (val) => {
  visible.value = val;
  if (val && props.permission) {
    Object.assign(formData, {
      id: props.permission.id,
      groupName: props.permission.groupName,
      name: props.permission.name,
      expression: props.permission.expression
    });
  } else if (val) {
    formData.id = null;
    formData.groupName = '';
    formData.name = '';
    formData.expression = '';
  }
});

const onModalClose = (refresh: boolean) => {
  visible.value = false;
  emit('update:open', false);
  setTimeout(() => {
    emit('close', refresh);
  }, 500);
};

const onSubmit = () => {
  formRef.value.submit();
};

const onFinish = async ({ validateResult, firstError }: SubmitContext) => {
  if (validateResult === true) {
    const data: any = { ...formData };
    
    const url = data.id ? api.permission.update : api.permission.create;
    
    const result = await request.post(url, data);
    showResult.show(result);
    
    if (result.status) {
      onModalClose(true);
    }
  }
};
</script>

// codebase/admin/src/pages/permission/PermissionEdit.tsx
import { useEffect, useState } from "react"
import { Modal, useRequest, useTranslation } from "../../components"
import { Button, Divider, Form, Input, Space, Typography, FormProps, App } from "antd"
import { CloseOutlined, SendOutlined } from "@ant-design/icons"
import { api } from "../../common/api"
import { AdminPermission, DefaultNS } from "../../common/I18NNamespace"

export type PermissionFormType = {
    id?: number | string,
    groupName?: string, 
    name?: string,
    expression? : string
}

export type PermissionEditType = {
    open: boolean,
    onClose: (refresh:boolean) => void,
    permission?: any
}   

/**
 * 添加，编辑角色
 * @returns 
 */
export const PermissionEdit : React.FC<PermissionEditType> = ({
    open,
    onClose, 
    permission
}) => {
    const [defaultValues, setDefaultValues] = useState<PermissionFormType>();


    const {t} = useTranslation(AdminPermission);
    const request = useRequest();
    const {message} = App.useApp();
    // const [visible, setVisible] = useState(open);
    const [form] = Form.useForm();

    const onModalClose = () => {
        // setVisible(false);
        onClose(false);
    }

    const onSubmit = () => {
        form.submit();
    } 

    const onFinish: FormProps<PermissionFormType>['onFinish'] = (values) => {

        let data = values as any;
        data.type = data.type * 1;

        // console.log(values);
        const create = async () => {
            let result = await request.post(
                data.id?api.permission.update:api.permission.create,
                data
            );
            if(result.status){
                message.success(result.msg);
                onClose(true);
            }else{
                message.error(result.msg);
            }
        }
        create();
    };
    
    useEffect(()=>{
        if(permission) {
            let values = {
                groupName: permission.groupName,
                name: permission.name,
                expression: permission.expression,
                id: permission.id,
            };
            setDefaultValues(values)
            form.setFieldsValue(values);
        }else if(open){
            setDefaultValues(null);
            form.resetFields();
        }
    }, [open]);

    if(open) {
        return <Modal open={open} onClose={onModalClose} title={t("添加角色")} width={400}>
            <>
                <div style={{width:'100%'}}>
                    <div style={{padding: "0px 20px 10px 20px", width: 340, margin: "0px auto"}}>
                        <Typography.Title level={4} style={{marginTop: 20, marginBottom: 20, textAlign: "center"}}>{t("添加角色")}</Typography.Title>
                        <Form<PermissionFormType> form = {form} layout='horizontal'
                            onFinish={onFinish}
                        >   
                            <Form.Item name="id" hidden={true}>
                                <Input></Input>
                            </Form.Item>
                            <Form.Item<PermissionFormType> label={t("分组名")} name="groupName"
                                rules={[{ required: true, message: t('分组名不能为空') }]}
                            >
                                <Input></Input>
                            </Form.Item>
                            <Form.Item<PermissionFormType> label={t("权限名")} name="name"
                                rules={[{ required: true, message: t('权限名不能为空') }]}
                            >
                                <Input></Input>
                            </Form.Item>
                            <Form.Item<PermissionFormType> label={t("表达式")} name="expression"
                                rules={[{ required: true, message: t('表达式不能为空') }]}
                            >
                                <Input></Input>
                            </Form.Item>
                        </Form>
                        <Divider />
                        <div style={{textAlign: 'right'}}>
                            <Space>
                                <Button onClick={onModalClose} icon={<CloseOutlined />}>{t("取消", DefaultNS)}</Button>
                                <Button onClick={onSubmit} type="primary" icon={<SendOutlined />}>{t("确定", DefaultNS)}</Button>
                            </Space>
                        </div>
                    </div>
                </div>
            </>
        </Modal>
    }else {
        return <></>
    }
}
