// codebase/admin-vue3/src/components/EditableTagItem.vue
<template>
  <div class="editable-tag-wrap" style="position: relative; padding-right: 30px">
    <template v-if="editing">
      <t-space align="center">
        <t-select
          v-model="localValue"
          :options="options"
          :style="{ minWidth: typeof width === 'number' ? width + 'px' : width || 'calc(100% - 50px)' }"
          @blur="onBlur"
        />
        <t-button theme="primary" variant="text" shape="square" @click="onClickEnter">
          <template #icon><t-icon name="check" /></template>
        </t-button>
      </t-space>
    </template>
    <template v-else>
      <TypeTag :options="options" :value="localValue" />
      <span style="position: absolute; top: 2px; right: 0;">
        <t-tooltip v-if="editable" :content="t('编辑')">
          <span style="cursor: pointer; margin-right: 5px;" @click="onEditIconClick">
            <t-icon name="edit" style="color: var(--td-brand-color)" />
          </span>
        </t-tooltip>
        <template v-if="copyable">
          <t-icon v-if="copyed" name="check" style="color: var(--td-success-color)" />
          <t-tooltip v-else :content="t('复制')">
            <span style="cursor: pointer;" @click="onCopy">
              <t-icon name="file-copy" class="copy-icon" style="color: var(--td-brand-color)" />
            </span>
          </t-tooltip>
        </template>
      </span>
    </template>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue';
import { useTranslation } from '@/hooks/useTranslation';
import TypeTag from './TypeTag.vue';

interface Props {
  value: string | number;
  options: any[];
  copyable?: boolean | 'CopyValue' | 'CopyLabel' | 'CopyAll';
  editable?: boolean;
  trigger?: 'click' | 'blur';
  width?: number | string;
}

const props = withDefaults(defineProps<Props>(), {
  copyable: false,
  editable: true,
  trigger: 'click'
});

const emit = defineEmits<{
  (e: 'change', val: string | number): void;
}>();

const { t } = useTranslation();
const editing = ref(false);
const localValue = ref(props.value);
const copyed = ref(false);

watch(() => props.value, (val) => {
  localValue.value = val;
});

const onEditIconClick = () => {
  editing.value = true;
};

const onEnter = () => {
  editing.value = false;
  if (localValue.value !== props.value) {
    emit('change', localValue.value);
  }
};

const onBlur = () => {
  if (props.trigger === 'blur') {
    onEnter();
  }
};

const onClickEnter = () => {
  if (props.trigger === 'click') {
    onEnter();
  }
};

const onCopy = () => {
  let text = "";
  const option = props.options.find(s => s.value === props.value);
  
  if (!option) {
    text = String(props.value);
  } else {
    if (props.copyable === 'CopyLabel') {
      text = String(t(option.label));
    } else if (props.copyable === 'CopyAll') {
      text = JSON.stringify(option);
    } else {
      text = String(props.value);
    }
  }

  navigator.clipboard.writeText(text);
  copyed.value = true;
  setTimeout(() => {
    copyed.value = false;
  }, 4000);
};
</script>

<style scoped>
.editable-tag-wrap .copy-icon {
  display: none;
}
.editable-tag-wrap:hover .copy-icon {
  display: inline-block;
}
</style>

// codebase/admin/src/components/wrap/EditableTagItem.tsx
import { useState, useTransition } from "react";
import { DictType } from "../../common/dict";
import { Button, Select, Space, Tooltip } from "antd";
import { CheckOutlined } from "@ant-design/icons";
import { TypeTag } from "./TypeTag";
import { CopyIcon, EditIcon } from "../icon/svg/Icons";
import { DefaultNS } from "../../common/I18NNamespace";
import { useTranslation } from "../../hooks/useTranslation";

/**
 * 可编辑的tag
 */
export const EditableTagItem : React.FC<{
    value: string | number,
    onChange?: (value: string | number) => void, 
    options: DictType[],
    i18nNamespace: string,
    copyable?: boolean | 'CopyValue' | 'CopyLabel' | 'CopyAll',
    trigger?: 'click' | 'blur',
    editable?: boolean,
    width?: number | string
}> = ({
    value, onChange, options, i18nNamespace, 
    copyable = false,
    editable = true,
    trigger = 'click', 
    width
}) => {

    const {t} = useTranslation(DefaultNS);
    const [editing, setEdting] = useState(false);
    const [localValue, setLocalValue] = useState(value);
    const [copyed, setCopyed] = useState(false);

    const onEditIconClick = () => {
        setEdting(true);
    }

    const onEnter = ()=> {
        setEdting(false);
        if(localValue !== value && onChange){
            onChange(localValue);
        }
    }

    const onBlur = () => {
        if(trigger == 'blur'){
            onEnter();
        }
    }

    const onClickEnter = () => {
        if(trigger == 'click'){
            onEnter();
        }
    }

    const onCopy = ()=> {
        let text = "";

        let option = options.find(s => s.value == value);
        if(!option){
            text = value + "";
        }else{
            if(copyable == 'CopyLabel'){
                text = option.label;
            }else if(copyable == 'CopyAll'){
                text = JSON.stringify(option);
            }else{
                text = value+"";
            }
        }

        navigator.clipboard.writeText(text);
        setCopyed(true);
        setTimeout(()=>{
            setCopyed(false);
        }, 4000)
    }

    if(editing){
        return (
            <Space.Compact block>
                <Select onChange={(value)=>setLocalValue(value)} value={localValue} options={options} 
                   style={{minWidth: width?width: 'calc(100% - 50px)'}}
                   onBlur={onBlur}
                ></Select>
                <Button icon={<CheckOutlined type="primary" />}
                    onClick={onClickEnter}
                ></Button>
            </Space.Compact>
        );
    }else{
        return (
            <>
            <style>{
                `.editable-tag-wrap .copy-icon{display:none;}
                .editable-tag-wrap:hover .copy-icon{display:inline;}
                `
            }</style>
            <div className="editable-tag-wrap" style={{position: 'relative', paddingRight: 30}}>
                <TypeTag options={options || []} I18Namespace={i18nNamespace}>{localValue}</TypeTag>
                <span style={{position: 'absolute', top: 2, right: 0}}>
                    {editable && <Tooltip title={t("编辑")}>
                        <span>
                            <EditIcon type="primary" ghost  onClick={onEditIconClick} style={{cursor: 'pointer', marginRight: 5}}/>
                        </span>
                    </Tooltip>}
                    {copyable ? (copyed ? (<CheckOutlined className="copy-icon" style={{color: "#00b96b"}}/>) 
                        : (
                        <Tooltip title={t("复制")}>
                            <span>
                                <CopyIcon type="primary" className="copy-icon" ghost onClick={ onCopy } style={{cursor: 'pointer'}} />
                            </span>
                        </Tooltip>
                        )) : <></>}
                </span>
            </div>
            </>
        );
    }

}
